// Security Knowledge Graph - 전체 구축 파일
// 아래 내용을 처음부터 끝까지 순서대로 실행하면 최종 프로토타입이 구축된다.
// 최종 기대값: Nodes 335 / Relationships 637 / Controls 248

// 01. Constraints
// Neo4j 5+/Cypher 25 기준

CREATE CONSTRAINT security_id_unique IF NOT EXISTS
FOR (n:Security) REQUIRE n.id IS UNIQUE;

CREATE CONSTRAINT framework_id_unique IF NOT EXISTS
FOR (n:Framework) REQUIRE n.id IS UNIQUE;

CREATE CONSTRAINT domain_id_unique IF NOT EXISTS
FOR (n:Domain) REQUIRE n.id IS UNIQUE;

CREATE CONSTRAINT category_id_unique IF NOT EXISTS
FOR (n:Category) REQUIRE n.id IS UNIQUE;

CREATE CONSTRAINT control_id_unique IF NOT EXISTS
FOR (n:Control) REQUIRE n.id IS UNIQUE;


// 02. Security / Domain / Category 구축

MERGE (s:Security {id: 'SECURITY'})
SET s.name = 'Security';

UNWIND [
  { id: 'GOV', name: '거버넌스·준수' },
  { id: 'RSK', name: '위험관리' },
  { id: 'AST', name: '자산·정보관리' },
  { id: 'HUM', name: '인적보안' },
  { id: 'SUP', name: '공급망·외부자' },
  { id: 'PHY', name: '물리·환경보안' },
  { id: 'IAM', name: '계정·접근통제' },
  { id: 'CRY', name: '암호화·키관리' },
  { id: 'OPS', name: '시스템·운영보안' },
  { id: 'NET', name: '네트워크·통신보안' },
  { id: 'LOG', name: '로그·모니터링' },
  { id: 'DEV', name: '개발·변경보안' },
  { id: 'INC', name: '사고대응' },
  { id: 'BCP', name: '백업·연속성·재해복구' },
  { id: 'DAT', name: '데이터보호·개인정보' },
  { id: 'CLD', name: '클라우드·가상화' }
] AS row
MERGE (d:Domain {id: row.id})
SET d.name = row.name
WITH d
MATCH (s:Security {id: 'SECURITY'})
MERGE (s)-[:HAS_DOMAIN]->(d);

UNWIND [
  { id: 'GOV-01', name: '정책·지침', domain_id: 'GOV', description: '정책, 조직, 책임, 경영진, 감사 및 준수' },
  { id: 'GOV-02', name: '조직·역할·경영진', domain_id: 'GOV', description: '정책, 조직, 책임, 경영진, 감사 및 준수' },
  { id: 'GOV-03', name: '감사·검토·개선', domain_id: 'GOV', description: '정책, 조직, 책임, 경영진, 감사 및 준수' },
  { id: 'GOV-04', name: '준수·문서·프로젝트', domain_id: 'GOV', description: '정책, 조직, 책임, 경영진, 감사 및 준수' },
  { id: 'RSK-01', name: '위험 식별·평가', domain_id: 'RSK', description: '위험의 식별·평가·처리 및 위협 정보' },
  { id: 'RSK-02', name: '위험 처리·위협정보', domain_id: 'RSK', description: '위험의 식별·평가·처리 및 위협 정보' },
  { id: 'AST-01', name: '자산 식별·목록', domain_id: 'AST', description: '자산과 정보의 식별, 분류, 사용 및 매체 관리' },
  { id: 'AST-02', name: '자산 분류·중요도', domain_id: 'AST', description: '자산과 정보의 식별, 분류, 사용 및 매체 관리' },
  { id: 'AST-03', name: '자산 사용·반납·매체', domain_id: 'AST', description: '자산과 정보의 식별, 분류, 사용 및 매체 관리' },
  { id: 'AST-04', name: '정보 분류·전송·기록보호', domain_id: 'AST', description: '자산과 정보의 식별, 분류, 사용 및 매체 관리' },
  { id: 'HUM-01', name: '채용·신원·서약', domain_id: 'HUM', description: '임직원 채용부터 퇴직까지의 인적 보안' },
  { id: 'HUM-02', name: '교육·인식', domain_id: 'HUM', description: '임직원 채용부터 퇴직까지의 인적 보안' },
  { id: 'HUM-03', name: '직무분리·주요직무', domain_id: 'HUM', description: '임직원 채용부터 퇴직까지의 인적 보안' },
  { id: 'HUM-04', name: '퇴직·직무변경·징계', domain_id: 'HUM', description: '임직원 채용부터 퇴직까지의 인적 보안' },
  { id: 'SUP-01', name: '업체 선정·계약', domain_id: 'SUP', description: '외부자, 위탁, 공급자 및 공급망 보안' },
  { id: 'SUP-02', name: '공급망·위탁', domain_id: 'SUP', description: '외부자, 위탁, 공급자 및 공급망 보안' },
  { id: 'SUP-03', name: '점검·서비스관리·종료', domain_id: 'SUP', description: '외부자, 위탁, 공급자 및 공급망 보안' },
  { id: 'PHY-01', name: '보호구역·출입통제', domain_id: 'PHY', description: '시설, 출입, 장비, 환경 및 물리적 보호' },
  { id: 'PHY-02', name: '시설·환경·전원', domain_id: 'PHY', description: '시설, 출입, 장비, 환경 및 물리적 보호' },
  { id: 'PHY-03', name: '물리 모니터링', domain_id: 'PHY', description: '시설, 출입, 장비, 환경 및 물리적 보호' },
  { id: 'PHY-04', name: '장비·외부자산·유지보수', domain_id: 'PHY', description: '시설, 출입, 장비, 환경 및 물리적 보호' },
  { id: 'IAM-01', name: '계정·식별관리', domain_id: 'IAM', description: '사용자 식별, 인증, 계정, 권한 및 접근 통제' },
  { id: 'IAM-02', name: '인증·비밀번호·MFA', domain_id: 'IAM', description: '사용자 식별, 인증, 계정, 권한 및 접근 통제' },
  { id: 'IAM-03', name: '권한·최소권한', domain_id: 'IAM', description: '사용자 식별, 인증, 계정, 권한 및 접근 통제' },
  { id: 'IAM-04', name: '특권·특수권한', domain_id: 'IAM', description: '사용자 식별, 인증, 계정, 권한 및 접근 통제' },
  { id: 'IAM-05', name: '정보·시스템 접근통제', domain_id: 'IAM', description: '사용자 식별, 인증, 계정, 권한 및 접근 통제' },
  { id: 'IAM-06', name: '원격접근·세션·소스코드', domain_id: 'IAM', description: '사용자 식별, 인증, 계정, 권한 및 접근 통제' },
  { id: 'CRY-01', name: '암호정책·저장암호화', domain_id: 'CRY', description: '암호화 적용과 암호키 관리' },
  { id: 'CRY-02', name: '전송 데이터 보호', domain_id: 'CRY', description: '암호화 적용과 암호키 관리' },
  { id: 'CRY-03', name: '암호키 관리', domain_id: 'CRY', description: '암호화 적용과 암호키 관리' },
  { id: 'OPS-01', name: '형상·패치·취약점', domain_id: 'OPS', description: '시스템 운영, 형상, 패치, 취약점 및 엔드포인트' },
  { id: 'OPS-02', name: '악성코드·엔드포인트', domain_id: 'OPS', description: '시스템 운영, 형상, 패치, 취약점 및 엔드포인트' },
  { id: 'OPS-03', name: '용량·성능', domain_id: 'OPS', description: '시스템 운영, 형상, 패치, 취약점 및 엔드포인트' },
  { id: 'OPS-04', name: '운영 소프트웨어·유틸리티', domain_id: 'OPS', description: '시스템 운영, 형상, 패치, 취약점 및 엔드포인트' },
  { id: 'OPS-05', name: '서버·DB·서비스 보안', domain_id: 'OPS', description: '시스템 운영, 형상, 패치, 취약점 및 엔드포인트' },
  { id: 'NET-01', name: '네트워크 접근통제', domain_id: 'NET', description: '네트워크 접근, 분리, 서비스 및 웹/통신 보안' },
  { id: 'NET-02', name: '네트워크·서비스 보안', domain_id: 'NET', description: '네트워크 접근, 분리, 서비스 및 웹/통신 보안' },
  { id: 'NET-03', name: '네트워크 분리·무선', domain_id: 'NET', description: '네트워크 접근, 분리, 서비스 및 웹/통신 보안' },
  { id: 'NET-04', name: '웹·인터넷 보안', domain_id: 'NET', description: '네트워크 접근, 분리, 서비스 및 웹/통신 보안' },
  { id: 'LOG-01', name: '로그 수집·보관·무결성', domain_id: 'LOG', description: '로그 수집·보관, 무결성, 모니터링 및 관제' },
  { id: 'LOG-02', name: '모니터링·이상징후·관제', domain_id: 'LOG', description: '로그 수집·보관, 무결성, 모니터링 및 관제' },
  { id: 'LOG-03', name: '시각 동기화', domain_id: 'LOG', description: '로그 수집·보관, 무결성, 모니터링 및 관제' },
  { id: 'DEV-01', name: '보안 요구사항·SDLC', domain_id: 'DEV', description: '개발 생명주기, 코딩, 테스트, 변경 및 개발환경' },
  { id: 'DEV-02', name: '보안 아키텍처', domain_id: 'DEV', description: '개발 생명주기, 코딩, 테스트, 변경 및 개발환경' },
  { id: 'DEV-03', name: '보안 코딩·테스트', domain_id: 'DEV', description: '개발 생명주기, 코딩, 테스트, 변경 및 개발환경' },
  { id: 'DEV-04', name: '개발·테스트·운영 분리', domain_id: 'DEV', description: '개발 생명주기, 코딩, 테스트, 변경 및 개발환경' },
  { id: 'DEV-05', name: '변경관리', domain_id: 'DEV', description: '개발 생명주기, 코딩, 테스트, 변경 및 개발환경' },
  { id: 'DEV-06', name: '위탁개발·테스트정보', domain_id: 'DEV', description: '개발 생명주기, 코딩, 테스트, 변경 및 개발환경' },
  { id: 'INC-01', name: '사고 대응체계·준비', domain_id: 'INC', description: '침해사고 준비, 평가, 대응, 보고 및 사후 개선' },
  { id: 'INC-02', name: '이벤트 평가·보고', domain_id: 'INC', description: '침해사고 준비, 평가, 대응, 보고 및 사후 개선' },
  { id: 'INC-03', name: '사고대응·증거수집', domain_id: 'INC', description: '침해사고 준비, 평가, 대응, 보고 및 사후 개선' },
  { id: 'INC-04', name: '사후개선·모의훈련', domain_id: 'INC', description: '침해사고 준비, 평가, 대응, 보고 및 사후 개선' },
  { id: 'BCP-01', name: '백업·복구', domain_id: 'BCP', description: '백업, 이중화, 업무연속성 및 재해복구' },
  { id: 'BCP-02', name: '이중화·복제', domain_id: 'BCP', description: '백업, 이중화, 업무연속성 및 재해복구' },
  { id: 'BCP-03', name: 'BIA·DRP·RTO/RPO', domain_id: 'BCP', description: '백업, 이중화, 업무연속성 및 재해복구' },
  { id: 'BCP-04', name: '업무연속성·재해복구훈련', domain_id: 'BCP', description: '백업, 이중화, 업무연속성 및 재해복구' },
  { id: 'DAT-01', name: '개인정보 수집·이용', domain_id: 'DAT', description: '개인정보와 중요 데이터의 수집, 이용, 제공, 보관, 파기 및 보호' },
  { id: 'DAT-02', name: '제3자 제공·위탁·국외이전', domain_id: 'DAT', description: '개인정보와 중요 데이터의 수집, 이용, 제공, 보관, 파기 및 보호' },
  { id: 'DAT-03', name: '보유·파기', domain_id: 'DAT', description: '개인정보와 중요 데이터의 수집, 이용, 제공, 보관, 파기 및 보호' },
  { id: 'DAT-04', name: '정보주체 권리보장', domain_id: 'DAT', description: '개인정보와 중요 데이터의 수집, 이용, 제공, 보관, 파기 및 보호' },
  { id: 'DAT-05', name: '데이터 마스킹·비식별화', domain_id: 'DAT', description: '개인정보와 중요 데이터의 수집, 이용, 제공, 보관, 파기 및 보호' },
  { id: 'DAT-06', name: '데이터 유출방지', domain_id: 'DAT', description: '개인정보와 중요 데이터의 수집, 이용, 제공, 보관, 파기 및 보호' },
  { id: 'DAT-07', name: '중요정보 처리·보호', domain_id: 'DAT', description: '개인정보와 중요 데이터의 수집, 이용, 제공, 보관, 파기 및 보호' },
  { id: 'CLD-01', name: '클라우드 거버넌스·책임', domain_id: 'CLD', description: '클라우드 서비스, 가상화, 테넌트 및 클라우드 자원 보호' },
  { id: 'CLD-02', name: '가상화·하이퍼바이저 보안', domain_id: 'CLD', description: '클라우드 서비스, 가상화, 테넌트 및 클라우드 자원 보호' },
  { id: 'CLD-03', name: '테넌트·자원 격리', domain_id: 'CLD', description: '클라우드 서비스, 가상화, 테넌트 및 클라우드 자원 보호' },
  { id: 'CLD-04', name: '클라우드 특화 보호조치', domain_id: 'CLD', description: '클라우드 서비스, 가상화, 테넌트 및 클라우드 자원 보호' }
] AS row
MERGE (c:Category {id: row.id})
SET c.name = row.name,
    c.description = row.description
WITH c, row
MATCH (d:Domain {id: row.domain_id})
MERGE (d)-[:HAS_CATEGORY]->(c);


// 03. Framework 노드 구축

UNWIND [
  { id: 'CASP', name: 'CASP' },
  { id: 'ISMS-P', name: 'ISMS-P' },
  { id: 'ISO27001', name: 'ISO/IEC 27001:2022' }
] AS row
MERGE (f:Framework {id: row.id})
SET f.name = row.name;


// 04. Control 248개 구축
// CASP 54 / ISMS-P 101 / ISO27001 93

UNWIND [
  { id: 'CASP-001', framework: 'CASP', control_id: 'CASP-001', title: '정보보호 및 개인정보보호 정책·지침 제/개정', original_level1: '정보보호 정책 및 조직', original_level2: '1.1 정보보호 정책 수립', original_detail: '정보보호 및 개인정보보호 정책·지침 제/개정', mapping_status: '프로토타입', note: null },
  { id: 'CASP-002', framework: 'CASP', control_id: 'CASP-002', title: '정보보호 정책의 최고경영자 승인 및 전사 공유', original_level1: '정보보호 정책 및 조직', original_level2: '1.1 정보보호 정책 수립', original_detail: '정보보호 정책의 최고경영자 승인 및 전사 공유', mapping_status: '프로토타입', note: null },
  { id: 'CASP-003', framework: 'CASP', control_id: 'CASP-003', title: 'CISO/CPO 임명 및 역할·권한 정의', original_level1: '정보보호 정책 및 조직', original_level2: '1.2 정보보호 조직 구성 및 역할 정의', original_detail: 'CISO/CPO 임명 및 역할·권한 정의', mapping_status: '프로토타입', note: null },
  { id: 'CASP-004', framework: 'CASP', control_id: 'CASP-004', title: '정보보호위원회 구성 및 정기 회의 운영', original_level1: '정보보호 정책 및 조직', original_level2: '1.2 정보보호 조직 구성 및 역할 정의', original_detail: '정보보호위원회 구성 및 정기 회의 운영', mapping_status: '프로토타입', note: null },
  { id: 'CASP-005', framework: 'CASP', control_id: 'CASP-005', title: '입사 시 보안서약서 작성 및 신원 검증', original_level1: '인적 보안', original_level2: '2.1 임직원 보안', original_detail: '입사 시 보안서약서 작성 및 신원 검증', mapping_status: '프로토타입', note: null },
  { id: 'CASP-006', framework: 'CASP', control_id: 'CASP-006', title: '정기 정보보호 교육 실시 및 이수 관리', original_level1: '인적 보안', original_level2: '2.1 임직원 보안', original_detail: '정기 정보보호 교육 실시 및 이수 관리', mapping_status: '프로토타입', note: null },
  { id: 'CASP-007', framework: 'CASP', control_id: 'CASP-007', title: '개발/운영/보안 직무 간 권한 분리', original_level1: '인적 보안', original_level2: '2.2 직무 분리 등', original_detail: '개발/운영/보안 직무 간 권한 분리', mapping_status: '프로토타입', note: null },
  { id: 'CASP-008', framework: 'CASP', control_id: 'CASP-008', title: '퇴직/보직 변경 시 즉시 계정 및 권한 회수', original_level1: '인적 보안', original_level2: '2.2 직무 분리 등', original_detail: '퇴직/보직 변경 시 즉시 계정 및 권한 회수', mapping_status: '프로토타입', note: null },
  { id: 'CASP-009', framework: 'CASP', control_id: 'CASP-009', title: '클라우드 자산(하드웨어, 소프트웨어, VM, 데이터 등) 식별 및 식별자 부여', original_level1: '자산 관리', original_level2: '3.1 클라우드 서비스 자산 식별 및 관리', original_detail: '클라우드 자산(하드웨어, 소프트웨어, VM, 데이터 등) 식별 및 식별자 부여', mapping_status: '프로토타입', note: null },
  { id: 'CASP-010', framework: 'CASP', control_id: 'CASP-010', title: '자산 관리대장 작성, 최신화 및 자산 중요도 평가', original_level1: '자산 관리', original_level2: '3.1 클라우드 서비스 자산 식별 및 관리', original_detail: '자산 관리대장 작성, 최신화 및 자산 중요도 평가', mapping_status: '프로토타입', note: null },
  { id: 'CASP-011', framework: 'CASP', control_id: 'CASP-011', title: '외주/협력업체 선정 시 보안 평가 및 계약서 내 보안 요구사항 명시', original_level1: '서비스 공급망 관리', original_level2: '4.1 외주 및 협력업체 보안 관리', original_detail: '외주/협력업체 선정 시 보안 평가 및 계약서 내 보안 요구사항 명시', mapping_status: '프로토타입', note: null },
  { id: 'CASP-012', framework: 'CASP', control_id: 'CASP-012', title: '위탁 업무/업체 주기적 보안 점검 및 계약 종료 시 데이터 파기 확인', original_level1: '서비스 공급망 관리', original_level2: '4.1 외주 및 협력업체 보안 관리', original_detail: '위탁 업무/업체 주기적 보안 점검 및 계약 종료 시 데이터 파기 확인', mapping_status: '프로토타입', note: null },
  { id: 'CASP-013', framework: 'CASP', control_id: 'CASP-013', title: '클라우드 환경 특성을 반영한 위협 및 취약점 식별', original_level1: '위험 관리', original_level2: '5.1 위험 식별 및 평가', original_detail: '클라우드 환경 특성을 반영한 위협 및 취약점 식별', mapping_status: '프로토타입', note: null },
  { id: 'CASP-014', framework: 'CASP', control_id: 'CASP-014', title: '정기적 위험 평가 수행 및 위험 수용 수준 설정', original_level1: '위험 관리', original_level2: '5.1 위험 식별 및 평가', original_detail: '정기적 위험 평가 수행 및 위험 수용 수준 설정', mapping_status: '프로토타입', note: null },
  { id: 'CASP-015', framework: 'CASP', control_id: 'CASP-015', title: '위험 처리 계획(RTP) 수립 및 이행 관리', original_level1: '위험 관리', original_level2: '5.2 위험 조치 절차', original_detail: '위험 처리 계획(RTP) 수립 및 이행 관리', mapping_status: '프로토타입', note: null },
  { id: 'CASP-016', framework: 'CASP', control_id: 'CASP-016', title: '잔여 위험에 대한 경영진 승인', original_level1: '위험 관리', original_level2: '5.2 위험 조치 절차', original_detail: '잔여 위험에 대한 경영진 승인', mapping_status: '프로토타입', note: null },
  { id: 'CASP-017', framework: 'CASP', control_id: 'CASP-017', title: '기본 계정/패스워드 변경 및 불필요한 서비스/포트 제거 (보안 형상 관리)', original_level1: '운영 보안', original_level2: '6.1 시스템 설정 관리 및 패치', original_detail: '기본 계정/패스워드 변경 및 불필요한 서비스/포트 제거 (보안 형상 관리)', mapping_status: '프로토타입', note: null },
  { id: 'CASP-018', framework: 'CASP', control_id: 'CASP-018', title: '최신 보안 패치 검증 및 정기 적용 절차', original_level1: '운영 보안', original_level2: '6.1 시스템 설정 관리 및 패치', original_detail: '최신 보안 패치 검증 및 정기 적용 절차', mapping_status: '프로토타입', note: null },
  { id: 'CASP-019', framework: 'CASP', control_id: 'CASP-019', title: '접속 로그, 작업 로그, 보안 로그 1년 이상 보관 및 백업', original_level1: '운영 보안', original_level2: '6.2 로그 보관 및 분석', original_detail: '접속 로그, 작업 로그, 보안 로그 1년 이상 보관 및 백업', mapping_status: '프로토타입', note: null },
  { id: 'CASP-020', framework: 'CASP', control_id: 'CASP-020', title: '로그 위·변조 방지 및 정기 모니터링/이상징후 분석', original_level1: '운영 보안', original_level2: '6.2 로그 보관 및 분석', original_detail: '로그 위·변조 방지 및 정기 모니터링/이상징후 분석', mapping_status: '프로토타입', note: null },
  { id: 'CASP-021', framework: 'CASP', control_id: 'CASP-021', title: '백업 정책 수립, 주기적 백업 수행 및 무결성 검증', original_level1: '운영 보안', original_level2: '6.3 백업 관리', original_detail: '백업 정책 수립, 주기적 백업 수행 및 무결성 검증', mapping_status: '프로토타입', note: null },
  { id: 'CASP-022', framework: 'CASP', control_id: 'CASP-022', title: '백업 데이터 소외 보관 및 복구 테스트 실시', original_level1: '운영 보안', original_level2: '6.3 백업 관리', original_detail: '백업 데이터 소외 보관 및 복구 테스트 실시', mapping_status: '프로토타입', note: null },
  { id: 'CASP-023', framework: 'CASP', control_id: 'CASP-023', title: '데이터센터/보호구역 출입 승인 절차 및 출입 기록 보관', original_level1: '물리적 보안', original_level2: '7.1 IDC 및 인프라 출입 통제', original_detail: '데이터센터/보호구역 출입 승인 절차 및 출입 기록 보관', mapping_status: '프로토타입', note: null },
  { id: 'CASP-024', framework: 'CASP', control_id: 'CASP-024', title: 'CCTV 모니터링 및 출입 통제 시스템 운영', original_level1: '물리적 보안', original_level2: '7.1 IDC 및 인프라 출입 통제', original_detail: 'CCTV 모니터링 및 출입 통제 시스템 운영', mapping_status: '프로토타입', note: null },
  { id: 'CASP-025', framework: 'CASP', control_id: 'CASP-025', title: 'UPS, 비상발전기 등 무정전 전원 설비 갖춤 및 정기 점검', original_level1: '물리적 보안', original_level2: '7.2 무정전 전원 및 환경 설비', original_detail: 'UPS, 비상발전기 등 무정전 전원 설비 갖춤 및 정기 점검', mapping_status: '프로토타입', note: null },
  { id: 'CASP-026', framework: 'CASP', control_id: 'CASP-026', title: '항온항습, 화재 감지 및 소화 설비 구비', original_level1: '물리적 보안', original_level2: '7.2 무정전 전원 및 환경 설비', original_detail: '항온항습, 화재 감지 및 소화 설비 구비', mapping_status: '프로토타입', note: null },
  { id: 'CASP-027', framework: 'CASP', control_id: 'CASP-027', title: '24x7 보안관제 체계 구축 및 보안장비(SIEM, ESM 등) 연동', original_level1: '침해사고 예방 및 대응', original_level2: '8.1 이벤트 모니터링 및 탐지', original_detail: '24x7 보안관제 체계 구축 및 보안장비(SIEM, ESM 등) 연동', mapping_status: '프로토타입', note: null },
  { id: 'CASP-028', framework: 'CASP', control_id: 'CASP-028', title: '임계치 초과 및 이상 행위 탐지 룰 설정', original_level1: '침해사고 예방 및 대응', original_level2: '8.1 이벤트 모니터링 및 탐지', original_detail: '임계치 초과 및 이상 행위 탐지 룰 설정', mapping_status: '프로토타입', note: null },
  { id: 'CASP-029', framework: 'CASP', control_id: 'CASP-029', title: '침해사고 대응 절차 수립 및 사고조사/보고 체계 구축', original_level1: '침해사고 예방 및 대응', original_level2: '8.2 침해사고 대응 및 모의훈련', original_detail: '침해사고 대응 절차 수립 및 사고조사/보고 체계 구축', mapping_status: '프로토타입', note: null },
  { id: 'CASP-030', framework: 'CASP', control_id: 'CASP-030', title: '연 1회 이상 침해사고 대비 모의훈련 실시 및 개선사항 반영', original_level1: '침해사고 예방 및 대응', original_level2: '8.2 침해사고 대응 및 모의훈련', original_detail: '연 1회 이상 침해사고 대비 모의훈련 실시 및 개선사항 반영', mapping_status: '프로토타입', note: null },
  { id: 'CASP-031', framework: 'CASP', control_id: 'CASP-031', title: '관리자/사용자 계정 생성·변경·삭제 절차 및 정기 계정 점검', original_level1: '접근 통제 및 계정 관리', original_level2: '9.1 사용자/관리자 계정 관리', original_detail: '관리자/사용자 계정 생성·변경·삭제 절차 및 정기 계정 점검', mapping_status: '프로토타입', note: null },
  { id: 'CASP-032', framework: 'CASP', control_id: 'CASP-032', title: '관리자 페이지 및 중요 시스템 접근 시 다중인증(MFA) 필수 적용', original_level1: '접근 통제 및 계정 관리', original_level2: '9.1 사용자/관리자 계정 관리', original_detail: '관리자 페이지 및 중요 시스템 접근 시 다중인증(MFA) 필수 적용', mapping_status: '프로토타입', note: null },
  { id: 'CASP-033', framework: 'CASP', control_id: 'CASP-033', title: '최소 권한 부여 원칙 및 특권 계정 사용 통제', original_level1: '접근 통제 및 계정 관리', original_level2: '9.2 접근 권한 제어 및 세션 관리', original_detail: '최소 권한 부여 원칙 및 특권 계정 사용 통제', mapping_status: '프로토타입', note: null },
  { id: 'CASP-034', framework: 'CASP', control_id: 'CASP-034', title: '일정 시간 미사용 시 세션 타임아웃(자동 로그아웃) 설정', original_level1: '접근 통제 및 계정 관리', original_level2: '9.2 접근 권한 제어 및 세션 관리', original_detail: '일정 시간 미사용 시 세션 타임아웃(자동 로그아웃) 설정', mapping_status: '프로토타입', note: null },
  { id: 'CASP-035', framework: 'CASP', control_id: 'CASP-035', title: '데이터 전송 시 구간 암호화(TLS/HTTPS 등) 적용', original_level1: '암호화 적용', original_level2: '10.1 전송/저장 데이터 암호화', original_detail: '데이터 전송 시 구간 암호화(TLS/HTTPS 등) 적용', mapping_status: '프로토타입', note: null },
  { id: 'CASP-036', framework: 'CASP', control_id: 'CASP-036', title: '데이터 저장 시 중요정보(비밀번호, 개인정보 등) 안전한 암호화 알고리즘 적용', original_level1: '암호화 적용', original_level2: '10.1 전송/저장 데이터 암호화', original_detail: '데이터 저장 시 중요정보(비밀번호, 개인정보 등) 안전한 암호화 알고리즘 적용', mapping_status: '프로토타입', note: null },
  { id: 'CASP-037', framework: 'CASP', control_id: 'CASP-037', title: '암호키 생성·배포·보관·주기적 교체·파기 절차 수립', original_level1: '암호화 적용', original_level2: '10.2 암호키 관리', original_detail: '암호키 생성·배포·보관·주기적 교체·파기 절차 수립', mapping_status: '프로토타입', note: null },
  { id: 'CASP-038', framework: 'CASP', control_id: 'CASP-038', title: '암호키에 대한 접근 권한 제한 및 안전한 저장소(KMS/HSM) 활용', original_level1: '암호화 적용', original_level2: '10.2 암호키 관리', original_detail: '암호키에 대한 접근 권한 제한 및 안전한 저장소(KMS/HSM) 활용', mapping_status: '프로토타입', note: null },
  { id: 'CASP-039', framework: 'CASP', control_id: 'CASP-039', title: '개발, 테스트, 운영 환경의 물리적/논리적 분리', original_level1: '시스템 도입 및 개발 보안', original_level2: '11.1 개발 환경 보안 및 보안 코딩', original_detail: '개발, 테스트, 운영 환경의 물리적/논리적 분리', mapping_status: '프로토타입', note: null },
  { id: 'CASP-040', framework: 'CASP', control_id: 'CASP-040', title: '시큐어 코딩 가이드 준수 및 소스코드 보안 취약점 진단', original_level1: '시스템 도입 및 개발 보안', original_level2: '11.1 개발 환경 보안 및 보안 코딩', original_detail: '시큐어 코딩 가이드 준수 및 소스코드 보안 취약점 진단', mapping_status: '프로토타입', note: null },
  { id: 'CASP-041', framework: 'CASP', control_id: 'CASP-041', title: '정기적인 OS, DB, WEB/WAS, 네트워크 웹/앱 취약점 점검', original_level1: '시스템 도입 및 개발 보안', original_level2: '11.2 취약점 점검 및 조치', original_detail: '정기적인 OS, DB, WEB/WAS, 네트워크 웹/앱 취약점 점검', mapping_status: '프로토타입', note: null },
  { id: 'CASP-042', framework: 'CASP', control_id: 'CASP-042', title: '식별된 취약점에 대한 조치 이행 및 조치 결과 재점검', original_level1: '시스템 도입 및 개발 보안', original_level2: '11.2 취약점 점검 및 조치', original_detail: '식별된 취약점에 대한 조치 이행 및 조치 결과 재점검', mapping_status: '프로토타입', note: null },
  { id: 'CASP-043', framework: 'CASP', control_id: 'CASP-043', title: '하이퍼바이저 최신 보안 패치 및 최소 기능만 활성화', original_level1: '가상화 보안', original_level2: '12.1 가상화 하이퍼바이저 보안', original_detail: '하이퍼바이저 최신 보안 패치 및 최소 기능만 활성화', mapping_status: '프로토타입', note: null },
  { id: 'CASP-044', framework: 'CASP', control_id: 'CASP-044', title: '하이퍼바이저 관리 콘솔 접근 통제 및 감사 로그 남김', original_level1: '가상화 보안', original_level2: '12.1 가상화 하이퍼바이저 보안', original_detail: '하이퍼바이저 관리 콘솔 접근 통제 및 감사 로그 남김', mapping_status: '프로토타입', note: null },
  { id: 'CASP-045', framework: 'CASP', control_id: 'CASP-045', title: '테넌트(고객) 간 가상 머신 및 네트워크(VLAN/VPC) 완전 격리', original_level1: '가상화 보안', original_level2: '12.2 가상 머신(VM) 간 격리', original_detail: '테넌트(고객) 간 가상 머신 및 네트워크(VLAN/VPC) 완전 격리', mapping_status: '프로토타입', note: null },
  { id: 'CASP-046', framework: 'CASP', control_id: 'CASP-046', title: 'VM 할당/해제 시 메모리 및 저장공간 완전 삭제(잔여 데이터 방지)', original_level1: '가상화 보안', original_level2: '12.2 가상 머신(VM) 간 격리', original_detail: 'VM 할당/해제 시 메모리 및 저장공간 완전 삭제(잔여 데이터 방지)', mapping_status: '프로토타입', note: null },
  { id: 'CASP-047', framework: 'CASP', control_id: 'CASP-047', title: '서비스 영향평가(BIA) 및 재해복구 계획(DRP) 수립', original_level1: '서비스 연속성 관리', original_level2: '13.1 재해복구 및 비상대응 계획', original_detail: '서비스 영향평가(BIA) 및 재해복구 계획(DRP) 수립', mapping_status: '프로토타입', note: null },
  { id: 'CASP-048', framework: 'CASP', control_id: 'CASP-048', title: '목표 복구 시간(RTO) 및 목표 복구 시점(RPO) 설정', original_level1: '서비스 연속성 관리', original_level2: '13.1 재해복구 및 비상대응 계획', original_detail: '목표 복구 시간(RTO) 및 목표 복구 시점(RPO) 설정', mapping_status: '프로토타입', note: null },
  { id: 'CASP-049', framework: 'CASP', control_id: 'CASP-049', title: '이중화(HA) 센터 또는 주/보조 센터 간 데이터 실시간/주기적 복제', original_level1: '서비스 연속성 관리', original_level2: '13.2 백업 및 복구 시스템 구축', original_detail: '이중화(HA) 센터 또는 주/보조 센터 간 데이터 실시간/주기적 복제', mapping_status: '프로토타입', note: null },
  { id: 'CASP-050', framework: 'CASP', control_id: 'CASP-050', title: '연 1회 이상 재해복구 모의훈련 및 복구 가능성 검증', original_level1: '서비스 연속성 관리', original_level2: '13.2 백업 및 복구 시스템 구축', original_detail: '연 1회 이상 재해복구 모의훈련 및 복구 가능성 검증', mapping_status: '프로토타입', note: null },
  { id: 'CASP-051', framework: 'CASP', control_id: 'CASP-051', title: '공공기관 전용 클라우드 존(Zone) 구축 및 민간 영역과 물리적/논리적 분리', original_level1: '공공기관용 추가 보호조치', original_level2: '14.1 공공 데이터 격리 및 물리적 망분리', original_detail: '공공기관 전용 클라우드 존(Zone) 구축 및 민간 영역과 물리적/논리적 분리', mapping_status: '프로토타입', note: null },
  { id: 'CASP-052', framework: 'CASP', control_id: 'CASP-052', title: '공공기관 전용 데이터독점 보장 및 저장 위치(국내 센터 제한) 규정 준수', original_level1: '공공기관용 추가 보호조치', original_level2: '14.1 공공 데이터 격리 및 물리적 망분리', original_detail: '공공기관 전용 데이터독점 보장 및 저장 위치(국내 센터 제한) 규정 준수', mapping_status: '프로토타입', note: null },
  { id: 'CASP-053', framework: 'CASP', control_id: 'CASP-053', title: '도입되는 보안 제품(방화벽, IPS 등)의 CC 인증 수렴 여부 확인', original_level1: '공공기관용 추가 보호조치', original_level2: '14.2 CC 인증 및 검증필 암호 모듈 적용', original_detail: '도입되는 보안 제품(방화벽, IPS 등)의 CC 인증 수렴 여부 확인', mapping_status: '프로토타입', note: null },
  { id: 'CASP-054', framework: 'CASP', control_id: 'CASP-054', title: '암호화 모듈 적용 시 국정원 검증필 암호모듈(KCMVP) 탑재 및 검증', original_level1: '공공기관용 추가 보호조치', original_level2: '14.2 CC 인증 및 검증필 암호 모듈 적용', original_detail: '암호화 모듈 적용 시 국정원 검증필 암호모듈(KCMVP) 탑재 및 검증', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-001', framework: 'ISMS-P', control_id: 'ISMSP-001', title: '최고경영자 참여', original_level1: '분야 1: 관리체계 수립 및 운영', original_level2: '1.1 관리체계 기반 마련', original_detail: '최고경영자 참여', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-002', framework: 'ISMS-P', control_id: 'ISMSP-002', title: '정보보호 및 개인정보보호 조직 구성', original_level1: '분야 1: 관리체계 수립 및 운영', original_level2: '1.1 관리체계 기반 마련', original_detail: '정보보호 및 개인정보보호 조직 구성', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-003', framework: 'ISMS-P', control_id: 'ISMSP-003', title: '책임자 지정', original_level1: '분야 1: 관리체계 수립 및 운영', original_level2: '1.1 관리체계 기반 마련', original_detail: '책임자 지정', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-004', framework: 'ISMS-P', control_id: 'ISMSP-004', title: '자원 할당', original_level1: '분야 1: 관리체계 수립 및 운영', original_level2: '1.1 관리체계 기반 마련', original_detail: '자원 할당', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-005', framework: 'ISMS-P', control_id: 'ISMSP-005', title: '범위 설정', original_level1: '분야 1: 관리체계 수립 및 운영', original_level2: '1.1 관리체계 기반 마련', original_detail: '범위 설정', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-006', framework: 'ISMS-P', control_id: 'ISMSP-006', title: '보고 및 공유', original_level1: '분야 1: 관리체계 수립 및 운영', original_level2: '1.1 관리체계 기반 마련', original_detail: '보고 및 공유', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-007', framework: 'ISMS-P', control_id: 'ISMSP-007', title: '자산 식별', original_level1: '분야 1: 관리체계 수립 및 운영', original_level2: '1.2 위험 관리', original_detail: '자산 식별', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-008', framework: 'ISMS-P', control_id: 'ISMSP-008', title: '위험 평가 절차', original_level1: '분야 1: 관리체계 수립 및 운영', original_level2: '1.2 위험 관리', original_detail: '위험 평가 절차', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-009', framework: 'ISMS-P', control_id: 'ISMSP-009', title: '위험 처리 계획', original_level1: '분야 1: 관리체계 수립 및 운영', original_level2: '1.2 위험 관리', original_detail: '위험 처리 계획', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-010', framework: 'ISMS-P', control_id: 'ISMSP-010', title: '위험 관리 체계 유지', original_level1: '분야 1: 관리체계 수립 및 운영', original_level2: '1.2 위험 관리', original_detail: '위험 관리 체계 유지', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-011', framework: 'ISMS-P', control_id: 'ISMSP-011', title: '정책 및 지침 시행', original_level1: '분야 1: 관리체계 수립 및 운영', original_level2: '1.3 관리체계 운영', original_detail: '정책 및 지침 시행', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-012', framework: 'ISMS-P', control_id: 'ISMSP-012', title: '임직원 보안 인식 및 교육', original_level1: '분야 1: 관리체계 수립 및 운영', original_level2: '1.3 관리체계 운영', original_detail: '임직원 보안 인식 및 교육', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-013', framework: 'ISMS-P', control_id: 'ISMSP-013', title: '일상적 보안 검토', original_level1: '분야 1: 관리체계 수립 및 운영', original_level2: '1.3 관리체계 운영', original_detail: '일상적 보안 검토', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-014', framework: 'ISMS-P', control_id: 'ISMSP-014', title: '내부 감사', original_level1: '분야 1: 관리체계 수립 및 운영', original_level2: '1.4 관리체계 점검 및 개선', original_detail: '내부 감사', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-015', framework: 'ISMS-P', control_id: 'ISMSP-015', title: '사후 조치 및 개선', original_level1: '분야 1: 관리체계 수립 및 운영', original_level2: '1.4 관리체계 점검 및 개선', original_detail: '사후 조치 및 개선', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-016', framework: 'ISMS-P', control_id: 'ISMSP-016', title: '경영진 검토 및 보고', original_level1: '분야 1: 관리체계 수립 및 운영', original_level2: '1.4 관리체계 점검 및 개선', original_detail: '경영진 검토 및 보고', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-017', framework: 'ISMS-P', control_id: 'ISMSP-017', title: '정보보호 및 개인정보보호 정책 수립', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.1 정책, 조직, 자산 관리', original_detail: '정보보호 및 개인정보보호 정책 수립', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-018', framework: 'ISMS-P', control_id: 'ISMSP-018', title: '조직 구성 및 역할 부여', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.1 정책, 조직, 자산 관리', original_detail: '조직 구성 및 역할 부여', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-019', framework: 'ISMS-P', control_id: 'ISMSP-019', title: '자산 목록 관리', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.1 정책, 조직, 자산 관리', original_detail: '자산 목록 관리', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-020', framework: 'ISMS-P', control_id: 'ISMSP-020', title: '자산 중요도 평가 및 식별', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.1 정책, 조직, 자산 관리', original_detail: '자산 중요도 평가 및 식별', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-021', framework: 'ISMS-P', control_id: 'ISMSP-021', title: '주요 직무자 관리', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.2 인적 보안', original_detail: '주요 직무자 관리', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-022', framework: 'ISMS-P', control_id: 'ISMSP-022', title: '보안 서약서 수령', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.2 인적 보안', original_detail: '보안 서약서 수령', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-023', framework: 'ISMS-P', control_id: 'ISMSP-023', title: '임직원 보안 교육 및 훈련', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.2 인적 보안', original_detail: '임직원 보안 교육 및 훈련', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-024', framework: 'ISMS-P', control_id: 'ISMSP-024', title: '퇴직 및 직무 이동 관리', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.2 인적 보안', original_detail: '퇴직 및 직무 이동 관리', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-025', framework: 'ISMS-P', control_id: 'ISMSP-025', title: '보안 위반자 제재', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.2 인적 보안', original_detail: '보안 위반자 제재', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-026', framework: 'ISMS-P', control_id: 'ISMSP-026', title: '신원 조사 및 적격성 검증', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.2 인적 보안', original_detail: '신원 조사 및 적격성 검증', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-027', framework: 'ISMS-P', control_id: 'ISMSP-027', title: '위탁 및 용역 업체 선정', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.3 외부자 보안', original_detail: '위탁 및 용역 업체 선정', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-028', framework: 'ISMS-P', control_id: 'ISMSP-028', title: '계약서 보안 요구사항 명시', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.3 외부자 보안', original_detail: '계약서 보안 요구사항 명시', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-029', framework: 'ISMS-P', control_id: 'ISMSP-029', title: '외부자 보안 상태 점검 및 감독', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.3 외부자 보안', original_detail: '외부자 보안 상태 점검 및 감독', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-030', framework: 'ISMS-P', control_id: 'ISMSP-030', title: '계약 종료 시 보안 조치', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.3 외부자 보안', original_detail: '계약 종료 시 보안 조치', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-031', framework: 'ISMS-P', control_id: 'ISMSP-031', title: '보호구역 지정 및 관리', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.4 물리 보안', original_detail: '보호구역 지정 및 관리', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-032', framework: 'ISMS-P', control_id: 'ISMSP-032', title: '통제구역 출입 통제', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.4 물리 보안', original_detail: '통제구역 출입 통제', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-033', framework: 'ISMS-P', control_id: 'ISMSP-033', title: '시설 및 설비 보호', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.4 물리 보안', original_detail: '시설 및 설비 보호', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-034', framework: 'ISMS-P', control_id: 'ISMSP-034', title: '장비 반출입 관리', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.4 물리 보안', original_detail: '장비 반출입 관리', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-035', framework: 'ISMS-P', control_id: 'ISMSP-035', title: '작업 공간 보안 및 도난 방지', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.4 물리 보안', original_detail: '작업 공간 보안 및 도난 방지', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-036', framework: 'ISMS-P', control_id: 'ISMSP-036', title: '사용자 식별 및 인증', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.5 인증 및 권한 관리', original_detail: '사용자 식별 및 인증', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-037', framework: 'ISMS-P', control_id: 'ISMSP-037', title: '비밀번호 규칙 및 계정 관리', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.5 인증 및 권한 관리', original_detail: '비밀번호 규칙 및 계정 관리', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-038', framework: 'ISMS-P', control_id: 'ISMSP-038', title: '접근 권한 최소 부여 및 관리', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.5 인증 및 권한 관리', original_detail: '접근 권한 최소 부여 및 관리', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-039', framework: 'ISMS-P', control_id: 'ISMSP-039', title: '특수 권한 관리', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.5 인증 및 권한 관리', original_detail: '특수 권한 관리', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-040', framework: 'ISMS-P', control_id: 'ISMSP-040', title: '계정 및 권한 정기 재검토', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.5 인증 및 권한 관리', original_detail: '계정 및 권한 정기 재검토', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-041', framework: 'ISMS-P', control_id: 'ISMSP-041', title: '네트워크 접근 통제', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.6 접근 통제', original_detail: '네트워크 접근 통제', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-042', framework: 'ISMS-P', control_id: 'ISMSP-042', title: '원격 근무 및 원격 접근 보안', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.6 접근 통제', original_detail: '원격 근무 및 원격 접근 보안', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-043', framework: 'ISMS-P', control_id: 'ISMSP-043', title: '무선랜 통제 및 접속 관리', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.6 접근 통제', original_detail: '무선랜 통제 및 접속 관리', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-044', framework: 'ISMS-P', control_id: 'ISMSP-044', title: '정보시스템 접근 통제', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.6 접근 통제', original_detail: '정보시스템 접근 통제', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-045', framework: 'ISMS-P', control_id: 'ISMSP-045', title: '응용프로그램 접근 통제', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.6 접근 통제', original_detail: '응용프로그램 접근 통제', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-046', framework: 'ISMS-P', control_id: 'ISMSP-046', title: '서버 및 네트워크 장비 접근 통제', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.6 접근 통제', original_detail: '서버 및 네트워크 장비 접근 통제', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-047', framework: 'ISMS-P', control_id: 'ISMSP-047', title: '세션 관리 및 자동 로그아웃', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.6 접근 통제', original_detail: '세션 관리 및 자동 로그아웃', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-048', framework: 'ISMS-P', control_id: 'ISMSP-048', title: '암호 정책 수립 및 적용', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.7 암호화 적용', original_detail: '암호 정책 수립 및 적용', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-049', framework: 'ISMS-P', control_id: 'ISMSP-049', title: '저장 데이터 암호화', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.7 암호화 적용', original_detail: '저장 데이터 암호화', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-050', framework: 'ISMS-P', control_id: 'ISMSP-050', title: '전송 데이터 암호화', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.7 암호화 적용', original_detail: '전송 데이터 암호화', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-051', framework: 'ISMS-P', control_id: 'ISMSP-051', title: '암호키 생성·보관·배포 및 관리', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.7 암호화 적용', original_detail: '암호키 생성·보관·배포 및 관리', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-052', framework: 'ISMS-P', control_id: 'ISMSP-052', title: '보안 요구사항 정의 및 분석', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.8 정보시스템 도입 및 개발 보안', original_detail: '보안 요구사항 정의 및 분석', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-053', framework: 'ISMS-P', control_id: 'ISMSP-053', title: '안전한 개발 환경 구축', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.8 정보시스템 도입 및 개발 보안', original_detail: '안전한 개발 환경 구축', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-054', framework: 'ISMS-P', control_id: 'ISMSP-054', title: '보안 코딩 및 취약점 점검', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.8 정보시스템 도입 및 개발 보안', original_detail: '보안 코딩 및 취약점 점검', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-055', framework: 'ISMS-P', control_id: 'ISMSP-055', title: '개발 및 운영 환경 분리', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.8 정보시스템 도입 및 개발 보안', original_detail: '개발 및 운영 환경 분리', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-056', framework: 'ISMS-P', control_id: 'ISMSP-056', title: '신규 시스템 검증 및 승인', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.8 정보시스템 도입 및 개발 보안', original_detail: '신규 시스템 검증 및 승인', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-057', framework: 'ISMS-P', control_id: 'ISMSP-057', title: '변경 관리 절차 수립 및 이행', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.9 시스템 및 서비스 운영 관리', original_detail: '변경 관리 절차 수립 및 이행', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-058', framework: 'ISMS-P', control_id: 'ISMSP-058', title: '백업 및 복구 테스트', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.9 시스템 및 서비스 운영 관리', original_detail: '백업 및 복구 테스트', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-059', framework: 'ISMS-P', control_id: 'ISMSP-059', title: '성능 및 용량 관리', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.9 시스템 및 서비스 운영 관리', original_detail: '성능 및 용량 관리', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-060', framework: 'ISMS-P', control_id: 'ISMSP-060', title: '패치 및 취약점 관리', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.9 시스템 및 서비스 운영 관리', original_detail: '패치 및 취약점 관리', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-061', framework: 'ISMS-P', control_id: 'ISMSP-061', title: '작업 절차서 작성 및 운영', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.9 시스템 및 서비스 운영 관리', original_detail: '작업 절차서 작성 및 운영', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-062', framework: 'ISMS-P', control_id: 'ISMSP-062', title: '외주 개발 및 시스템 운영 관리', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.9 시스템 및 서비스 운영 관리', original_detail: '외주 개발 및 시스템 운영 관리', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-063', framework: 'ISMS-P', control_id: 'ISMSP-063', title: '매체 관리 및 안전한 파기', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.9 시스템 및 서비스 운영 관리', original_detail: '매체 관리 및 안전한 파기', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-064', framework: 'ISMS-P', control_id: 'ISMSP-064', title: '악성코드 통제 및 대응', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.10 시스템 및 서비스 보안 관리', original_detail: '악성코드 통제 및 대응', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-065', framework: 'ISMS-P', control_id: 'ISMSP-065', title: '정보시스템 로그 보관 및 관리', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.10 시스템 및 서비스 보안 관리', original_detail: '정보시스템 로그 보관 및 관리', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-066', framework: 'ISMS-P', control_id: 'ISMSP-066', title: '로그 분석 및 이상 징후 모니터링', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.10 시스템 및 서비스 보안 관리', original_detail: '로그 분석 및 이상 징후 모니터링', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-067', framework: 'ISMS-P', control_id: 'ISMSP-067', title: '시각 동기화 (NTP)', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.10 시스템 및 서비스 보안 관리', original_detail: '시각 동기화 (NTP)', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-068', framework: 'ISMS-P', control_id: 'ISMSP-068', title: '네트워크 보안 장비 설정 및 관리', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.10 시스템 및 서비스 보안 관리', original_detail: '네트워크 보안 장비 설정 및 관리', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-069', framework: 'ISMS-P', control_id: 'ISMSP-069', title: '서버 및 시스템 접근 통제', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.10 시스템 및 서비스 보안 관리', original_detail: '서버 및 시스템 접근 통제', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-070', framework: 'ISMS-P', control_id: 'ISMSP-070', title: '데이터베이스 보안 관리', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.10 시스템 및 서비스 보안 관리', original_detail: '데이터베이스 보안 관리', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-071', framework: 'ISMS-P', control_id: 'ISMSP-071', title: '웹 서비스 보안 및 방화벽 설정', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.10 시스템 및 서비스 보안 관리', original_detail: '웹 서비스 보안 및 방화벽 설정', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-072', framework: 'ISMS-P', control_id: 'ISMSP-072', title: '공개 서버 관리', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.10 시스템 및 서비스 보안 관리', original_detail: '공개 서버 관리', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-073', framework: 'ISMS-P', control_id: 'ISMSP-073', title: '침해사고 대응 체계 구축', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.11 사고 예방 및 대응', original_detail: '침해사고 대응 체계 구축', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-074', framework: 'ISMS-P', control_id: 'ISMSP-074', title: '이상 징후 모니터링', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.11 사고 예방 및 대응', original_detail: '이상 징후 모니터링', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-075', framework: 'ISMS-P', control_id: 'ISMSP-075', title: '침해사고 모의훈련 실시', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.11 사고 예방 및 대응', original_detail: '침해사고 모의훈련 실시', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-076', framework: 'ISMS-P', control_id: 'ISMSP-076', title: '침해사고 보고 및 통지 절차', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.11 사고 예방 및 대응', original_detail: '침해사고 보고 및 통지 절차', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-077', framework: 'ISMS-P', control_id: 'ISMSP-077', title: '침해사고 원인 분석 및 재발 방지', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.11 사고 예방 및 대응', original_detail: '침해사고 원인 분석 및 재발 방지', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-078', framework: 'ISMS-P', control_id: 'ISMSP-078', title: '재해복구 및 비상대응 계획 수립', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.12 재해 복구', original_detail: '재해복구 및 비상대응 계획 수립', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-079', framework: 'ISMS-P', control_id: 'ISMSP-079', title: '백업 체계 구축 및 주기적 복구 테스트', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.12 재해 복구', original_detail: '백업 체계 구축 및 주기적 복구 테스트', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-080', framework: 'ISMS-P', control_id: 'ISMSP-080', title: '서비스 연속성 유지 방안 마련', original_level1: '분야 2: 보호대책 요구사항', original_level2: '2.12 재해 복구', original_detail: '서비스 연속성 유지 방안 마련', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-081', framework: 'ISMS-P', control_id: 'ISMSP-081', title: '개인정보 최소 수집 제한', original_level1: '분야 3: 개인정보 처리단계별 요구사항', original_level2: '3.1 개인정보 수집 시 보호조치', original_detail: '개인정보 최소 수집 제한', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-082', framework: 'ISMS-P', control_id: 'ISMSP-082', title: '동의 요건 준수 및 고지사항 명시', original_level1: '분야 3: 개인정보 처리단계별 요구사항', original_level2: '3.1 개인정보 수집 시 보호조치', original_detail: '동의 요건 준수 및 고지사항 명시', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-083', framework: 'ISMS-P', control_id: 'ISMSP-083', title: '고유식별정보 및 주민등록번호 처리 제한', original_level1: '분야 3: 개인정보 처리단계별 요구사항', original_level2: '3.1 개인정보 수집 시 보호조치', original_detail: '고유식별정보 및 주민등록번호 처리 제한', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-084', framework: 'ISMS-P', control_id: 'ISMSP-084', title: '민감정보 처리 제한', original_level1: '분야 3: 개인정보 처리단계별 요구사항', original_level2: '3.1 개인정보 수집 시 보호조치', original_detail: '민감정보 처리 제한', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-085', framework: 'ISMS-P', control_id: 'ISMSP-085', title: '목적 외 이용 및 제공 제한', original_level1: '분야 3: 개인정보 처리단계별 요구사항', original_level2: '3.2 개인정보 보유 및 이용 시 보호조치', original_detail: '목적 외 이용 및 제공 제한', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-086', framework: 'ISMS-P', control_id: 'ISMSP-086', title: '개인정보 처리위탁 관리 및 공개', original_level1: '분야 3: 개인정보 처리단계별 요구사항', original_level2: '3.2 개인정보 보유 및 이용 시 보호조치', original_detail: '개인정보 처리위탁 관리 및 공개', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-087', framework: 'ISMS-P', control_id: 'ISMSP-087', title: '개인정보 다운로드 및 간출 관리', original_level1: '분야 3: 개인정보 처리단계별 요구사항', original_level2: '3.2 개인정보 보유 및 이용 시 보호조치', original_detail: '개인정보 다운로드 및 간출 관리', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-088', framework: 'ISMS-P', control_id: 'ISMSP-088', title: '개인정보 영향평가 수행', original_level1: '분야 3: 개인정보 처리단계별 요구사항', original_level2: '3.2 개인정보 보유 및 이용 시 보호조치', original_detail: '개인정보 영향평가 수행', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-089', framework: 'ISMS-P', control_id: 'ISMSP-089', title: '동의 철회 및 회원 탈퇴 보장', original_level1: '분야 3: 개인정보 처리단계별 요구사항', original_level2: '3.2 개인정보 보유 및 이용 시 보호조치', original_detail: '동의 철회 및 회원 탈퇴 보장', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-090', framework: 'ISMS-P', control_id: 'ISMSP-090', title: '개인정보 간출 및 외부 전달 통제', original_level1: '분야 3: 개인정보 처리단계별 요구사항', original_level2: '3.2 개인정보 보유 및 이용 시 보호조치', original_detail: '개인정보 간출 및 외부 전달 통제', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-091', framework: 'ISMS-P', control_id: 'ISMSP-091', title: '제3자 제공 동의 수령 및 안전조치', original_level1: '분야 3: 개인정보 처리단계별 요구사항', original_level2: '3.3 개인정보 제공 시 보호조치', original_detail: '제3자 제공 동의 수령 및 안전조치', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-092', framework: 'ISMS-P', control_id: 'ISMSP-092', title: '개인정보 국외 이전 요건 충족', original_level1: '분야 3: 개인정보 처리단계별 요구사항', original_level2: '3.3 개인정보 제공 시 보호조치', original_detail: '개인정보 국외 이전 요건 충족', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-093', framework: 'ISMS-P', control_id: 'ISMSP-093', title: '제공 목적 달성 후 안전한 처리 확인', original_level1: '분야 3: 개인정보 처리단계별 요구사항', original_level2: '3.3 개인정보 제공 시 보호조치', original_detail: '제공 목적 달성 후 안전한 처리 확인', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-094', framework: 'ISMS-P', control_id: 'ISMSP-094', title: '파기 기한 준수 및 기준 수립', original_level1: '분야 3: 개인정보 처리단계별 요구사항', original_level2: '3.4 개인정보 파기 시 보호조치', original_detail: '파기 기한 준수 및 기준 수립', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-095', framework: 'ISMS-P', control_id: 'ISMSP-095', title: '복구 불가능한 안전한 파기 방법 적용', original_level1: '분야 3: 개인정보 처리단계별 요구사항', original_level2: '3.4 개인정보 파기 시 보호조치', original_detail: '복구 불가능한 안전한 파기 방법 적용', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-096', framework: 'ISMS-P', control_id: 'ISMSP-096', title: '파기 결과 확인 및 기록 보존', original_level1: '분야 3: 개인정보 처리단계별 요구사항', original_level2: '3.4 개인정보 파기 시 보호조치', original_detail: '파기 결과 확인 및 기록 보존', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-097', framework: 'ISMS-P', control_id: 'ISMSP-097', title: '개인정보 열람 및 정정·삭제 요구 대응', original_level1: '분야 3: 개인정보 처리단계별 요구사항', original_level2: '3.5 정보주체 권리 보장', original_detail: '개인정보 열람 및 정정·삭제 요구 대응', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-098', framework: 'ISMS-P', control_id: 'ISMSP-098', title: '처리정지 요구 대응 절차 수립', original_level1: '분야 3: 개인정보 처리단계별 요구사항', original_level2: '3.5 정보주체 권리 보장', original_detail: '처리정지 요구 대응 절차 수립', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-099', framework: 'ISMS-P', control_id: 'ISMSP-099', title: '권리 행사 방법 및 절차 안내', original_level1: '분야 3: 개인정보 처리단계별 요구사항', original_level2: '3.5 정보주체 권리 보장', original_detail: '권리 행사 방법 및 절차 안내', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-100', framework: 'ISMS-P', control_id: 'ISMSP-100', title: '정보주체 요구 대응 기록 관리', original_level1: '분야 3: 개인정보 처리단계별 요구사항', original_level2: '3.5 정보주체 권리 보장', original_detail: '정보주체 요구 대응 기록 관리', mapping_status: '프로토타입', note: null },
  { id: 'ISMSP-101', framework: 'ISMS-P', control_id: 'ISMSP-101', title: '법정대리인 권리 행사 보장', original_level1: '분야 3: 개인정보 처리단계별 요구사항', original_level2: '3.5 정보주체 권리 보장', original_detail: '법정대리인 권리 행사 보장', mapping_status: '프로토타입', note: null },
  { id: 'A.5.1', framework: 'ISO27001', control_id: 'A.5.1', title: '정보보호 정책 (Policies for information security)', original_level1: '조직적 통제 (A.5)', original_level2: null, original_detail: '정보보호 정책 (Policies for information security)', mapping_status: '프로토타입', note: null },
  { id: 'A.5.2', framework: 'ISO27001', control_id: 'A.5.2', title: '정보보호 역할 및 책임 (Information security roles and responsibilities)', original_level1: '조직적 통제 (A.5)', original_level2: null, original_detail: '정보보호 역할 및 책임 (Information security roles and responsibilities)', mapping_status: '프로토타입', note: null },
  { id: 'A.5.3', framework: 'ISO27001', control_id: 'A.5.3', title: '직무 분리 (Segregation of duties)', original_level1: '조직적 통제 (A.5)', original_level2: null, original_detail: '직무 분리 (Segregation of duties)', mapping_status: '프로토타입', note: null },
  { id: 'A.5.4', framework: 'ISO27001', control_id: 'A.5.4', title: '경영진의 책임 (Management responsibilities)', original_level1: '조직적 통제 (A.5)', original_level2: null, original_detail: '경영진의 책임 (Management responsibilities)', mapping_status: '프로토타입', note: null },
  { id: 'A.5.5', framework: 'ISO27001', control_id: 'A.5.5', title: '당국과의 연락 (Contact with authorities)', original_level1: '조직적 통제 (A.5)', original_level2: null, original_detail: '당국과의 연락 (Contact with authorities)', mapping_status: '프로토타입', note: null },
  { id: 'A.5.6', framework: 'ISO27001', control_id: 'A.5.6', title: '특수 관심 집단과의 연락 (Contact with special interest groups)', original_level1: '조직적 통제 (A.5)', original_level2: null, original_detail: '특수 관심 집단과의 연락 (Contact with special interest groups)', mapping_status: '프로토타입', note: null },
  { id: 'A.5.7', framework: 'ISO27001', control_id: 'A.5.7', title: '위협 인텔리전스 (Threat intelligence)', original_level1: '조직적 통제 (A.5)', original_level2: null, original_detail: '위협 인텔리전스 (Threat intelligence)', mapping_status: '프로토타입', note: null },
  { id: 'A.5.8', framework: 'ISO27001', control_id: 'A.5.8', title: '프로젝트 관리의 정보보호 (Information security in project management)', original_level1: '조직적 통제 (A.5)', original_level2: null, original_detail: '프로젝트 관리의 정보보호 (Information security in project management)', mapping_status: '프로토타입', note: null },
  { id: 'A.5.9', framework: 'ISO27001', control_id: 'A.5.9', title: '정보 및 기타 관련 자산의 목록 (Inventory of information and other associated assets)', original_level1: '조직적 통제 (A.5)', original_level2: null, original_detail: '정보 및 기타 관련 자산의 목록 (Inventory of information and other associated assets)', mapping_status: '프로토타입', note: null },
  { id: 'A.5.10', framework: 'ISO27001', control_id: 'A.5.10', title: '정보 및 기타 관련 자산의 허용된 사용 (Acceptable use of information and other associated assets)', original_level1: '조직적 통제 (A.5)', original_level2: null, original_detail: '정보 및 기타 관련 자산의 허용된 사용 (Acceptable use of information and other associated assets)', mapping_status: '프로토타입', note: null },
  { id: 'A.5.11', framework: 'ISO27001', control_id: 'A.5.11', title: '자산의 반납 (Return of assets)', original_level1: '조직적 통제 (A.5)', original_level2: null, original_detail: '자산의 반납 (Return of assets)', mapping_status: '프로토타입', note: null },
  { id: 'A.5.12', framework: 'ISO27001', control_id: 'A.5.12', title: '정보의 분류 (Classification of information)', original_level1: '조직적 통제 (A.5)', original_level2: null, original_detail: '정보의 분류 (Classification of information)', mapping_status: '프로토타입', note: null },
  { id: 'A.5.13', framework: 'ISO27001', control_id: 'A.5.13', title: '정보의 라벨링 (Labeling of information)', original_level1: '조직적 통제 (A.5)', original_level2: null, original_detail: '정보의 라벨링 (Labeling of information)', mapping_status: '프로토타입', note: null },
  { id: 'A.5.14', framework: 'ISO27001', control_id: 'A.5.14', title: '정보 전송 (Information transfer)', original_level1: '조직적 통제 (A.5)', original_level2: null, original_detail: '정보 전송 (Information transfer)', mapping_status: '프로토타입', note: null },
  { id: 'A.5.15', framework: 'ISO27001', control_id: 'A.5.15', title: '접근 통제 (Access control)', original_level1: '조직적 통제 (A.5)', original_level2: null, original_detail: '접근 통제 (Access control)', mapping_status: '프로토타입', note: null },
  { id: 'A.5.16', framework: 'ISO27001', control_id: 'A.5.16', title: '자격 증명 관리 (Identity management)', original_level1: '조직적 통제 (A.5)', original_level2: null, original_detail: '자격 증명 관리 (Identity management)', mapping_status: '프로토타입', note: null },
  { id: 'A.5.17', framework: 'ISO27001', control_id: 'A.5.17', title: '인증 정보 관리 (Authentication information)', original_level1: '조직적 통제 (A.5)', original_level2: null, original_detail: '인증 정보 관리 (Authentication information)', mapping_status: '프로토타입', note: null },
  { id: 'A.5.18', framework: 'ISO27001', control_id: 'A.5.18', title: '접근 권한 (Access rights)', original_level1: '조직적 통제 (A.5)', original_level2: null, original_detail: '접근 권한 (Access rights)', mapping_status: '프로토타입', note: null },
  { id: 'A.5.19', framework: 'ISO27001', control_id: 'A.5.19', title: '공급자 관계에서의 정보보호 (Information security in supplier relationships)', original_level1: '조직적 통제 (A.5)', original_level2: null, original_detail: '공급자 관계에서의 정보보호 (Information security in supplier relationships)', mapping_status: '프로토타입', note: null },
  { id: 'A.5.20', framework: 'ISO27001', control_id: 'A.5.20', title: '공급자 합의서 내 보안 처리 (Addressing information security within supplier agreements)', original_level1: '조직적 통제 (A.5)', original_level2: null, original_detail: '공급자 합의서 내 보안 처리 (Addressing information security within supplier agreements)', mapping_status: '프로토타입', note: null },
  { id: 'A.5.21', framework: 'ISO27001', control_id: 'A.5.21', title: 'ICT 공급망 보안 관리 (Managing information security in the ICT supply chain)', original_level1: '조직적 통제 (A.5)', original_level2: null, original_detail: 'ICT 공급망 보안 관리 (Managing information security in the ICT supply chain)', mapping_status: '프로토타입', note: null },
  { id: 'A.5.22', framework: 'ISO27001', control_id: 'A.5.22', title: '공급자 서비스 관리 및 모니터링 (Monitoring, review and change management of supplier services)', original_level1: '조직적 통제 (A.5)', original_level2: null, original_detail: '공급자 서비스 관리 및 모니터링 (Monitoring, review and change management of supplier services)', mapping_status: '프로토타입', note: null },
  { id: 'A.5.23', framework: 'ISO27001', control_id: 'A.5.23', title: '클라우드 서비스 이용 보안 (Information security for use of cloud services)', original_level1: '조직적 통제 (A.5)', original_level2: null, original_detail: '클라우드 서비스 이용 보안 (Information security for use of cloud services)', mapping_status: '프로토타입', note: null },
  { id: 'A.5.24', framework: 'ISO27001', control_id: 'A.5.24', title: '정보보호 침해사고 관리 기획 및 준비 (Information security incident management planning and preparation)', original_level1: '조직적 통제 (A.5)', original_level2: null, original_detail: '정보보호 침해사고 관리 기획 및 준비 (Information security incident management planning and preparation)', mapping_status: '프로토타입', note: null },
  { id: 'A.5.25', framework: 'ISO27001', control_id: 'A.5.25', title: '정보보호 사건 평가 및 결정 (Assessment and decision on information security events)', original_level1: '조직적 통제 (A.5)', original_level2: null, original_detail: '정보보호 사건 평가 및 결정 (Assessment and decision on information security events)', mapping_status: '프로토타입', note: null },
  { id: 'A.5.26', framework: 'ISO27001', control_id: 'A.5.26', title: '정보보호 침해사고 대응 (Response to information security incidents)', original_level1: '조직적 통제 (A.5)', original_level2: null, original_detail: '정보보호 침해사고 대응 (Response to information security incidents)', mapping_status: '프로토타입', note: null },
  { id: 'A.5.27', framework: 'ISO27001', control_id: 'A.5.27', title: '정보보호 침해사고로부터의 학습 (Learning from information security incidents)', original_level1: '조직적 통제 (A.5)', original_level2: null, original_detail: '정보보호 침해사고로부터의 학습 (Learning from information security incidents)', mapping_status: '프로토타입', note: null },
  { id: 'A.5.28', framework: 'ISO27001', control_id: 'A.5.28', title: '증거 수집 (Collection of evidence)', original_level1: '조직적 통제 (A.5)', original_level2: null, original_detail: '증거 수집 (Collection of evidence)', mapping_status: '프로토타입', note: null },
  { id: 'A.5.29', framework: 'ISO27001', control_id: 'A.5.29', title: '혼란 중 정보보호 (Information security during disruption)', original_level1: '조직적 통제 (A.5)', original_level2: null, original_detail: '혼란 중 정보보호 (Information security during disruption)', mapping_status: '프로토타입', note: null },
  { id: 'A.5.30', framework: 'ISO27001', control_id: 'A.5.30', title: 'ICT 비즈니스 연속성 대비 (ICT readiness for business continuity)', original_level1: '조직적 통제 (A.5)', original_level2: null, original_detail: 'ICT 비즈니스 연속성 대비 (ICT readiness for business continuity)', mapping_status: '프로토타입', note: null },
  { id: 'A.5.31', framework: 'ISO27001', control_id: 'A.5.31', title: '법적, 규제적, 계약적 요구사항 식별 (Legal, statutory, regulatory and contractual requirements)', original_level1: '조직적 통제 (A.5)', original_level2: null, original_detail: '법적, 규제적, 계약적 요구사항 식별 (Legal, statutory, regulatory and contractual requirements)', mapping_status: '프로토타입', note: null },
  { id: 'A.5.32', framework: 'ISO27001', control_id: 'A.5.32', title: '지식재산권 (Intellectual property rights)', original_level1: '조직적 통제 (A.5)', original_level2: null, original_detail: '지식재산권 (Intellectual property rights)', mapping_status: '프로토타입', note: null },
  { id: 'A.5.33', framework: 'ISO27001', control_id: 'A.5.33', title: '기록 보호 (Protection of records)', original_level1: '조직적 통제 (A.5)', original_level2: null, original_detail: '기록 보호 (Protection of records)', mapping_status: '프로토타입', note: null },
  { id: 'A.5.34', framework: 'ISO27001', control_id: 'A.5.34', title: '개인식별정보(PII) 및 프라이버시 보호 (Privacy and protection of PII)', original_level1: '조직적 통제 (A.5)', original_level2: null, original_detail: '개인식별정보(PII) 및 프라이버시 보호 (Privacy and protection of PII)', mapping_status: '프로토타입', note: null },
  { id: 'A.5.35', framework: 'ISO27001', control_id: 'A.5.35', title: '정보보호의 독립적 검토 (Independent review of information security)', original_level1: '조직적 통제 (A.5)', original_level2: null, original_detail: '정보보호의 독립적 검토 (Independent review of information security)', mapping_status: '프로토타입', note: null },
  { id: 'A.5.36', framework: 'ISO27001', control_id: 'A.5.36', title: '정보보호 정책 및 표준 준수 (Compliance with policies and standards for information security)', original_level1: '조직적 통제 (A.5)', original_level2: null, original_detail: '정보보호 정책 및 표준 준수 (Compliance with policies and standards for information security)', mapping_status: '프로토타입', note: null },
  { id: 'A.5.37', framework: 'ISO27001', control_id: 'A.5.37', title: '문서화된 운영 절차 (Documented operating procedures)', original_level1: '조직적 통제 (A.5)', original_level2: null, original_detail: '문서화된 운영 절차 (Documented operating procedures)', mapping_status: '프로토타입', note: null },
  { id: 'A.6.1', framework: 'ISO27001', control_id: 'A.6.1', title: '채용 전 검증 (Screening)', original_level1: '인적 통제 (A.6)', original_level2: null, original_detail: '채용 전 검증 (Screening)', mapping_status: '프로토타입', note: null },
  { id: 'A.6.2', framework: 'ISO27001', control_id: 'A.6.2', title: '고용 계약 조건 (Terms and conditions of employment)', original_level1: '인적 통제 (A.6)', original_level2: null, original_detail: '고용 계약 조건 (Terms and conditions of employment)', mapping_status: '프로토타입', note: null },
  { id: 'A.6.3', framework: 'ISO27001', control_id: 'A.6.3', title: '정보보호 인식, 교육 및 훈련 (Information security awareness, education and training)', original_level1: '인적 통제 (A.6)', original_level2: null, original_detail: '정보보호 인식, 교육 및 훈련 (Information security awareness, education and training)', mapping_status: '프로토타입', note: null },
  { id: 'A.6.4', framework: 'ISO27001', control_id: 'A.6.4', title: '징계 절차 (Disciplinary process)', original_level1: '인적 통제 (A.6)', original_level2: null, original_detail: '징계 절차 (Disciplinary process)', mapping_status: '프로토타입', note: null },
  { id: 'A.6.5', framework: 'ISO27001', control_id: 'A.6.5', title: '퇴직 또는 직무 변경 후의 책임 (Responsibilities after termination or change of employment)', original_level1: '인적 통제 (A.6)', original_level2: null, original_detail: '퇴직 또는 직무 변경 후의 책임 (Responsibilities after termination or change of employment)', mapping_status: '프로토타입', note: null },
  { id: 'A.6.6', framework: 'ISO27001', control_id: 'A.6.6', title: '기밀유지 또는 비개시 협약 (Confidentiality or non-disclosure agreements)', original_level1: '인적 통제 (A.6)', original_level2: null, original_detail: '기밀유지 또는 비개시 협약 (Confidentiality or non-disclosure agreements)', mapping_status: '프로토타입', note: null },
  { id: 'A.6.7', framework: 'ISO27001', control_id: 'A.6.7', title: '원격 근무 (Remote working)', original_level1: '인적 통제 (A.6)', original_level2: null, original_detail: '원격 근무 (Remote working)', mapping_status: '프로토타입', note: null },
  { id: 'A.6.8', framework: 'ISO27001', control_id: 'A.6.8', title: '정보보호 사건 보고 (Information security event reporting)', original_level1: '인적 통제 (A.6)', original_level2: null, original_detail: '정보보호 사건 보고 (Information security event reporting)', mapping_status: '프로토타입', note: null },
  { id: 'A.7.1', framework: 'ISO27001', control_id: 'A.7.1', title: '물리적 보안 경계 (Physical security perimeters)', original_level1: '물리적 통제 (A.7)', original_level2: null, original_detail: '물리적 보안 경계 (Physical security perimeters)', mapping_status: '프로토타입', note: null },
  { id: 'A.7.2', framework: 'ISO27001', control_id: 'A.7.2', title: '물리적 출입 (Physical entry)', original_level1: '물리적 통제 (A.7)', original_level2: null, original_detail: '물리적 출입 (Physical entry)', mapping_status: '프로토타입', note: null },
  { id: 'A.7.3', framework: 'ISO27001', control_id: 'A.7.3', title: '사무실, 공간 및 시설의 보안 (Securing offices, rooms and facilities)', original_level1: '물리적 통제 (A.7)', original_level2: null, original_detail: '사무실, 공간 및 시설의 보안 (Securing offices, rooms and facilities)', mapping_status: '프로토타입', note: null },
  { id: 'A.7.4', framework: 'ISO27001', control_id: 'A.7.4', title: '물리적 보안 모니터링 (Physical security monitoring)', original_level1: '물리적 통제 (A.7)', original_level2: null, original_detail: '물리적 보안 모니터링 (Physical security monitoring)', mapping_status: '프로토타입', note: null },
  { id: 'A.7.5', framework: 'ISO27001', control_id: 'A.7.5', title: '물리적 및 환경적 위협에 대한 보호 (Protecting against physical and environmental threats)', original_level1: '물리적 통제 (A.7)', original_level2: null, original_detail: '물리적 및 환경적 위협에 대한 보호 (Protecting against physical and environmental threats)', mapping_status: '프로토타입', note: null },
  { id: 'A.7.6', framework: 'ISO27001', control_id: 'A.7.6', title: '보호 구역에서의 작업 (Working in secure areas)', original_level1: '물리적 통제 (A.7)', original_level2: null, original_detail: '보호 구역에서의 작업 (Working in secure areas)', mapping_status: '프로토타입', note: null },
  { id: 'A.7.7', framework: 'ISO27001', control_id: 'A.7.7', title: '클리어 데스크 및 클리어 스크린 (Clear desk and clear screen)', original_level1: '물리적 통제 (A.7)', original_level2: null, original_detail: '클리어 데스크 및 클리어 스크린 (Clear desk and clear screen)', mapping_status: '프로토타입', note: null },
  { id: 'A.7.8', framework: 'ISO27001', control_id: 'A.7.8', title: '장비의 배치 및 보호 (Equipment siting and protection)', original_level1: '물리적 통제 (A.7)', original_level2: null, original_detail: '장비의 배치 및 보호 (Equipment siting and protection)', mapping_status: '프로토타입', note: null },
  { id: 'A.7.9', framework: 'ISO27001', control_id: 'A.7.9', title: '사업장 외 자산의 보안 (Security of assets off-premises)', original_level1: '물리적 통제 (A.7)', original_level2: null, original_detail: '사업장 외 자산의 보안 (Security of assets off-premises)', mapping_status: '프로토타입', note: null },
  { id: 'A.7.10', framework: 'ISO27001', control_id: 'A.7.10', title: '저장 매체 (Storage media)', original_level1: '물리적 통제 (A.7)', original_level2: null, original_detail: '저장 매체 (Storage media)', mapping_status: '프로토타입', note: null },
  { id: 'A.7.11', framework: 'ISO27001', control_id: 'A.7.11', title: '지원 설비 (Supporting utilities)', original_level1: '물리적 통제 (A.7)', original_level2: null, original_detail: '지원 설비 (Supporting utilities)', mapping_status: '프로토타입', note: null },
  { id: 'A.7.12', framework: 'ISO27001', control_id: 'A.7.12', title: '케이블 보안 (Cabling security)', original_level1: '물리적 통제 (A.7)', original_level2: null, original_detail: '케이블 보안 (Cabling security)', mapping_status: '프로토타입', note: null },
  { id: 'A.7.13', framework: 'ISO27001', control_id: 'A.7.13', title: '장비 유지보수 (Equipment maintenance)', original_level1: '물리적 통제 (A.7)', original_level2: null, original_detail: '장비 유지보수 (Equipment maintenance)', mapping_status: '프로토타입', note: null },
  { id: 'A.7.14', framework: 'ISO27001', control_id: 'A.7.14', title: '자산의 안전한 파기 또는 재사용 (Secure disposal or re-use of equipment)', original_level1: '물리적 통제 (A.7)', original_level2: null, original_detail: '자산의 안전한 파기 또는 재사용 (Secure disposal or re-use of equipment)', mapping_status: '프로토타입', note: null },
  { id: 'A.8.1', framework: 'ISO27001', control_id: 'A.8.1', title: '사용자 엔드포인트 장치 (User endpoint devices)', original_level1: '기술적 통제 (A.8)', original_level2: null, original_detail: '사용자 엔드포인트 장치 (User endpoint devices)', mapping_status: '프로토타입', note: null },
  { id: 'A.8.2', framework: 'ISO27001', control_id: 'A.8.2', title: '특권 접근 권한 (Privileged access rights)', original_level1: '기술적 통제 (A.8)', original_level2: null, original_detail: '특권 접근 권한 (Privileged access rights)', mapping_status: '프로토타입', note: null },
  { id: 'A.8.3', framework: 'ISO27001', control_id: 'A.8.3', title: '정보 접근 제한 (Information access restriction)', original_level1: '기술적 통제 (A.8)', original_level2: null, original_detail: '정보 접근 제한 (Information access restriction)', mapping_status: '프로토타입', note: null },
  { id: 'A.8.4', framework: 'ISO27001', control_id: 'A.8.4', title: '소스 코드 접근 (Access to source code)', original_level1: '기술적 통제 (A.8)', original_level2: null, original_detail: '소스 코드 접근 (Access to source code)', mapping_status: '프로토타입', note: null },
  { id: 'A.8.5', framework: 'ISO27001', control_id: 'A.8.5', title: '강력한 인증 (Secure authentication)', original_level1: '기술적 통제 (A.8)', original_level2: null, original_detail: '강력한 인증 (Secure authentication)', mapping_status: '프로토타입', note: null },
  { id: 'A.8.6', framework: 'ISO27001', control_id: 'A.8.6', title: '용량 관리 (Capacity management)', original_level1: '기술적 통제 (A.8)', original_level2: null, original_detail: '용량 관리 (Capacity management)', mapping_status: '프로토타입', note: null },
  { id: 'A.8.7', framework: 'ISO27001', control_id: 'A.8.7', title: '악성 코드 방지 (Protection against malware)', original_level1: '기술적 통제 (A.8)', original_level2: null, original_detail: '악성 코드 방지 (Protection against malware)', mapping_status: '프로토타입', note: null },
  { id: 'A.8.8', framework: 'ISO27001', control_id: 'A.8.8', title: '기술적 취약점 관리 (Management of technical vulnerabilities)', original_level1: '기술적 통제 (A.8)', original_level2: null, original_detail: '기술적 취약점 관리 (Management of technical vulnerabilities)', mapping_status: '프로토타입', note: null },
  { id: 'A.8.9', framework: 'ISO27001', control_id: 'A.8.9', title: '형상 관리 (Configuration management)', original_level1: '기술적 통제 (A.8)', original_level2: null, original_detail: '형상 관리 (Configuration management)', mapping_status: '프로토타입', note: null },
  { id: 'A.8.10', framework: 'ISO27001', control_id: 'A.8.10', title: '정보 삭제 (Information deletion)', original_level1: '기술적 통제 (A.8)', original_level2: null, original_detail: '정보 삭제 (Information deletion)', mapping_status: '프로토타입', note: null },
  { id: 'A.8.11', framework: 'ISO27001', control_id: 'A.8.11', title: '데이터 마스킹 (Data masking)', original_level1: '기술적 통제 (A.8)', original_level2: null, original_detail: '데이터 마스킹 (Data masking)', mapping_status: '프로토타입', note: null },
  { id: 'A.8.12', framework: 'ISO27001', control_id: 'A.8.12', title: '데이터 유출 방지 (Data leakage prevention - DLP)', original_level1: '기술적 통제 (A.8)', original_level2: null, original_detail: '데이터 유출 방지 (Data leakage prevention - DLP)', mapping_status: '프로토타입', note: null },
  { id: 'A.8.13', framework: 'ISO27001', control_id: 'A.8.13', title: '백업 (Information backup)', original_level1: '기술적 통제 (A.8)', original_level2: null, original_detail: '백업 (Information backup)', mapping_status: '프로토타입', note: null },
  { id: 'A.8.14', framework: 'ISO27001', control_id: 'A.8.14', title: '정보 처리 시설의 이중화 (Redundancy of information processing facilities)', original_level1: '기술적 통제 (A.8)', original_level2: null, original_detail: '정보 처리 시설의 이중화 (Redundancy of information processing facilities)', mapping_status: '프로토타입', note: null },
  { id: 'A.8.15', framework: 'ISO27001', control_id: 'A.8.15', title: '로깅 (Logging)', original_level1: '기술적 통제 (A.8)', original_level2: null, original_detail: '로깅 (Logging)', mapping_status: '프로토타입', note: null },
  { id: 'A.8.16', framework: 'ISO27001', control_id: 'A.8.16', title: '활동 모니터링 (Monitoring activities)', original_level1: '기술적 통제 (A.8)', original_level2: null, original_detail: '활동 모니터링 (Monitoring activities)', mapping_status: '프로토타입', note: null },
  { id: 'A.8.17', framework: 'ISO27001', control_id: 'A.8.17', title: '시각 동기화 (Clock synchronization)', original_level1: '기술적 통제 (A.8)', original_level2: null, original_detail: '시각 동기화 (Clock synchronization)', mapping_status: '프로토타입', note: null },
  { id: 'A.8.18', framework: 'ISO27001', control_id: 'A.8.18', title: '유틸리티 프로그램의 사용 (Use of privileged utility programs)', original_level1: '기술적 통제 (A.8)', original_level2: null, original_detail: '유틸리티 프로그램의 사용 (Use of privileged utility programs)', mapping_status: '프로토타입', note: null },
  { id: 'A.8.19', framework: 'ISO27001', control_id: 'A.8.19', title: '운영 시스템의 소프트웨어 설치 (Installation of software on operational systems)', original_level1: '기술적 통제 (A.8)', original_level2: null, original_detail: '운영 시스템의 소프트웨어 설치 (Installation of software on operational systems)', mapping_status: '프로토타입', note: null },
  { id: 'A.8.20', framework: 'ISO27001', control_id: 'A.8.20', title: '네트워크 보안 (Networks security)', original_level1: '기술적 통제 (A.8)', original_level2: null, original_detail: '네트워크 보안 (Networks security)', mapping_status: '프로토타입', note: null },
  { id: 'A.8.21', framework: 'ISO27001', control_id: 'A.8.21', title: '네트워크 서비스의 보안 (Security of network services)', original_level1: '기술적 통제 (A.8)', original_level2: null, original_detail: '네트워크 서비스의 보안 (Security of network services)', mapping_status: '프로토타입', note: null },
  { id: 'A.8.22', framework: 'ISO27001', control_id: 'A.8.22', title: '네트워크 분리 (Segregation of networks)', original_level1: '기술적 통제 (A.8)', original_level2: null, original_detail: '네트워크 분리 (Segregation of networks)', mapping_status: '프로토타입', note: null },
  { id: 'A.8.23', framework: 'ISO27001', control_id: 'A.8.23', title: '웹 필터링 (Web filtering)', original_level1: '기술적 통제 (A.8)', original_level2: null, original_detail: '웹 필터링 (Web filtering)', mapping_status: '프로토타입', note: null },
  { id: 'A.8.24', framework: 'ISO27001', control_id: 'A.8.24', title: '암호화 사용 (Use of cryptography)', original_level1: '기술적 통제 (A.8)', original_level2: null, original_detail: '암호화 사용 (Use of cryptography)', mapping_status: '프로토타입', note: null },
  { id: 'A.8.25', framework: 'ISO27001', control_id: 'A.8.25', title: '개발 생명주기의 보안 (Secure development life cycle)', original_level1: '기술적 통제 (A.8)', original_level2: null, original_detail: '개발 생명주기의 보안 (Secure development life cycle)', mapping_status: '프로토타입', note: null },
  { id: 'A.8.26', framework: 'ISO27001', control_id: 'A.8.26', title: '애플리케이션 보안 요구사항 (Application security requirements)', original_level1: '기술적 통제 (A.8)', original_level2: null, original_detail: '애플리케이션 보안 요구사항 (Application security requirements)', mapping_status: '프로토타입', note: null },
  { id: 'A.8.27', framework: 'ISO27001', control_id: 'A.8.27', title: '보안 시스템 아키텍처 및 엔지니어링 원칙 (Secure system architecture and engineering principles)', original_level1: '기술적 통제 (A.8)', original_level2: null, original_detail: '보안 시스템 아키텍처 및 엔지니어링 원칙 (Secure system architecture and engineering principles)', mapping_status: '프로토타입', note: null },
  { id: 'A.8.28', framework: 'ISO27001', control_id: 'A.8.28', title: '보안 코딩 (Secure coding)', original_level1: '기술적 통제 (A.8)', original_level2: null, original_detail: '보안 코딩 (Secure coding)', mapping_status: '프로토타입', note: null },
  { id: 'A.8.29', framework: 'ISO27001', control_id: 'A.8.29', title: '개발 및 테스트 시 보안 검증 (Security testing in development and acceptance)', original_level1: '기술적 통제 (A.8)', original_level2: null, original_detail: '개발 및 테스트 시 보안 검증 (Security testing in development and acceptance)', mapping_status: '프로토타입', note: null },
  { id: 'A.8.30', framework: 'ISO27001', control_id: 'A.8.30', title: '위탁 개발 (Outsourced development)', original_level1: '기술적 통제 (A.8)', original_level2: null, original_detail: '위탁 개발 (Outsourced development)', mapping_status: '프로토타입', note: null },
  { id: 'A.8.31', framework: 'ISO27001', control_id: 'A.8.31', title: '개발, 테스트 및 운영 환경의 분리 (Separation of development, testing and operational environments)', original_level1: '기술적 통제 (A.8)', original_level2: null, original_detail: '개발, 테스트 및 운영 환경의 분리 (Separation of development, testing and operational environments)', mapping_status: '프로토타입', note: null },
  { id: 'A.8.32', framework: 'ISO27001', control_id: 'A.8.32', title: '변경 관리 (Change management)', original_level1: '기술적 통제 (A.8)', original_level2: null, original_detail: '변경 관리 (Change management)', mapping_status: '프로토타입', note: null },
  { id: 'A.8.33', framework: 'ISO27001', control_id: 'A.8.33', title: '테스트 정보 (Test information)', original_level1: '기술적 통제 (A.8)', original_level2: null, original_detail: '테스트 정보 (Test information)', mapping_status: '프로토타입', note: null },
  { id: 'A.8.34', framework: 'ISO27001', control_id: 'A.8.34', title: '감사 테스트 중 정보시스템 보호 (Protection of information systems during audit testing)', original_level1: '기술적 통제 (A.8)', original_level2: null, original_detail: '감사 테스트 중 정보시스템 보호 (Protection of information systems during audit testing)', mapping_status: '프로토타입', note: null }
] AS row
MERGE (c:Control {id: row.id})
SET c.framework = row.framework,
    c.control_id = row.control_id,
    c.title = row.title,
    c.original_level1 = row.original_level1,
    c.original_level2 = row.original_level2,
    c.original_detail = row.original_detail,
    c.mapping_status = row.mapping_status,
    c.note = row.note;


// 05. Framework -> Control 연결

MATCH (c:Control)
MATCH (f:Framework {id: c.framework})
MERGE (f)-[:HAS_CONTROL]->(c);


// 06. Primary Mapping
// 모든 Control은 정확히 하나의 Category에 BELONGS_TO로 연결한다.
// 총 248개. 본 매핑은 프로토타입의 수동 의미 판단이며 공식 crosswalk가 아니다.

UNWIND [
  { control_id: 'CASP-001', category_id: 'GOV-01' },
  { control_id: 'CASP-002', category_id: 'GOV-02' },
  { control_id: 'CASP-003', category_id: 'GOV-02' },
  { control_id: 'CASP-004', category_id: 'GOV-02' },
  { control_id: 'CASP-005', category_id: 'HUM-01' },
  { control_id: 'CASP-006', category_id: 'HUM-02' },
  { control_id: 'CASP-007', category_id: 'HUM-03' },
  { control_id: 'CASP-008', category_id: 'HUM-04' },
  { control_id: 'CASP-009', category_id: 'AST-01' },
  { control_id: 'CASP-010', category_id: 'AST-02' },
  { control_id: 'CASP-011', category_id: 'SUP-01' },
  { control_id: 'CASP-012', category_id: 'SUP-03' },
  { control_id: 'CASP-013', category_id: 'RSK-01' },
  { control_id: 'CASP-014', category_id: 'RSK-01' },
  { control_id: 'CASP-015', category_id: 'RSK-02' },
  { control_id: 'CASP-016', category_id: 'RSK-02' },
  { control_id: 'CASP-017', category_id: 'OPS-01' },
  { control_id: 'CASP-018', category_id: 'OPS-01' },
  { control_id: 'CASP-019', category_id: 'LOG-01' },
  { control_id: 'CASP-020', category_id: 'LOG-01' },
  { control_id: 'CASP-021', category_id: 'BCP-01' },
  { control_id: 'CASP-022', category_id: 'BCP-01' },
  { control_id: 'CASP-023', category_id: 'PHY-01' },
  { control_id: 'CASP-024', category_id: 'PHY-01' },
  { control_id: 'CASP-025', category_id: 'PHY-02' },
  { control_id: 'CASP-026', category_id: 'PHY-02' },
  { control_id: 'CASP-027', category_id: 'LOG-02' },
  { control_id: 'CASP-028', category_id: 'LOG-02' },
  { control_id: 'CASP-029', category_id: 'INC-01' },
  { control_id: 'CASP-030', category_id: 'LOG-02' },
  { control_id: 'CASP-031', category_id: 'IAM-01' },
  { control_id: 'CASP-032', category_id: 'IAM-02' },
  { control_id: 'CASP-033', category_id: 'IAM-03' },
  { control_id: 'CASP-034', category_id: 'IAM-06' },
  { control_id: 'CASP-035', category_id: 'CRY-02' },
  { control_id: 'CASP-036', category_id: 'CRY-01' },
  { control_id: 'CASP-037', category_id: 'CRY-03' },
  { control_id: 'CASP-038', category_id: 'CRY-03' },
  { control_id: 'CASP-039', category_id: 'DEV-04' },
  { control_id: 'CASP-040', category_id: 'DEV-03' },
  { control_id: 'CASP-041', category_id: 'DEV-03' },
  { control_id: 'CASP-042', category_id: 'DEV-03' },
  { control_id: 'CASP-043', category_id: 'CLD-02' },
  { control_id: 'CASP-044', category_id: 'CLD-02' },
  { control_id: 'CASP-045', category_id: 'CLD-03' },
  { control_id: 'CASP-046', category_id: 'DAT-06' },
  { control_id: 'CASP-047', category_id: 'BCP-03' },
  { control_id: 'CASP-048', category_id: 'BCP-03' },
  { control_id: 'CASP-049', category_id: 'BCP-02' },
  { control_id: 'CASP-050', category_id: 'BCP-04' },
  { control_id: 'CASP-051', category_id: 'CLD-03' },
  { control_id: 'CASP-052', category_id: 'CLD-03' },
  { control_id: 'CASP-053', category_id: 'CLD-04' },
  { control_id: 'CASP-054', category_id: 'CLD-04' },
  { control_id: 'ISMSP-001', category_id: 'GOV-02' },
  { control_id: 'ISMSP-002', category_id: 'GOV-02' },
  { control_id: 'ISMSP-003', category_id: 'GOV-02' },
  { control_id: 'ISMSP-004', category_id: 'GOV-02' },
  { control_id: 'ISMSP-005', category_id: 'GOV-02' },
  { control_id: 'ISMSP-006', category_id: 'GOV-02' },
  { control_id: 'ISMSP-007', category_id: 'AST-01' },
  { control_id: 'ISMSP-008', category_id: 'RSK-01' },
  { control_id: 'ISMSP-009', category_id: 'RSK-02' },
  { control_id: 'ISMSP-010', category_id: 'RSK-01' },
  { control_id: 'ISMSP-011', category_id: 'GOV-01' },
  { control_id: 'ISMSP-012', category_id: 'HUM-02' },
  { control_id: 'ISMSP-013', category_id: 'GOV-03' },
  { control_id: 'ISMSP-014', category_id: 'GOV-03' },
  { control_id: 'ISMSP-015', category_id: 'GOV-03' },
  { control_id: 'ISMSP-016', category_id: 'GOV-03' },
  { control_id: 'ISMSP-017', category_id: 'GOV-01' },
  { control_id: 'ISMSP-018', category_id: 'GOV-02' },
  { control_id: 'ISMSP-019', category_id: 'AST-01' },
  { control_id: 'ISMSP-020', category_id: 'AST-02' },
  { control_id: 'ISMSP-021', category_id: 'HUM-03' },
  { control_id: 'ISMSP-022', category_id: 'HUM-01' },
  { control_id: 'ISMSP-023', category_id: 'HUM-02' },
  { control_id: 'ISMSP-024', category_id: 'HUM-04' },
  { control_id: 'ISMSP-025', category_id: 'HUM-04' },
  { control_id: 'ISMSP-026', category_id: 'HUM-01' },
  { control_id: 'ISMSP-027', category_id: 'SUP-01' },
  { control_id: 'ISMSP-028', category_id: 'SUP-01' },
  { control_id: 'ISMSP-029', category_id: 'SUP-03' },
  { control_id: 'ISMSP-030', category_id: 'SUP-03' },
  { control_id: 'ISMSP-031', category_id: 'PHY-01' },
  { control_id: 'ISMSP-032', category_id: 'PHY-01' },
  { control_id: 'ISMSP-033', category_id: 'PHY-02' },
  { control_id: 'ISMSP-034', category_id: 'PHY-01' },
  { control_id: 'ISMSP-035', category_id: 'PHY-02' },
  { control_id: 'ISMSP-036', category_id: 'IAM-01' },
  { control_id: 'ISMSP-037', category_id: 'IAM-02' },
  { control_id: 'ISMSP-038', category_id: 'IAM-03' },
  { control_id: 'ISMSP-039', category_id: 'IAM-04' },
  { control_id: 'ISMSP-040', category_id: 'IAM-03' },
  { control_id: 'ISMSP-041', category_id: 'NET-01' },
  { control_id: 'ISMSP-042', category_id: 'IAM-06' },
  { control_id: 'ISMSP-043', category_id: 'NET-03' },
  { control_id: 'ISMSP-044', category_id: 'IAM-05' },
  { control_id: 'ISMSP-045', category_id: 'IAM-05' },
  { control_id: 'ISMSP-046', category_id: 'NET-01' },
  { control_id: 'ISMSP-047', category_id: 'IAM-06' },
  { control_id: 'ISMSP-048', category_id: 'CRY-01' },
  { control_id: 'ISMSP-049', category_id: 'CRY-01' },
  { control_id: 'ISMSP-050', category_id: 'CRY-02' },
  { control_id: 'ISMSP-051', category_id: 'CRY-03' },
  { control_id: 'ISMSP-052', category_id: 'DEV-01' },
  { control_id: 'ISMSP-053', category_id: 'DEV-01' },
  { control_id: 'ISMSP-054', category_id: 'DEV-03' },
  { control_id: 'ISMSP-055', category_id: 'DEV-04' },
  { control_id: 'ISMSP-056', category_id: 'DEV-03' },
  { control_id: 'ISMSP-057', category_id: 'DEV-05' },
  { control_id: 'ISMSP-058', category_id: 'BCP-01' },
  { control_id: 'ISMSP-059', category_id: 'OPS-03' },
  { control_id: 'ISMSP-060', category_id: 'OPS-01' },
  { control_id: 'ISMSP-061', category_id: 'GOV-04' },
  { control_id: 'ISMSP-062', category_id: 'DEV-06' },
  { control_id: 'ISMSP-063', category_id: 'AST-03' },
  { control_id: 'ISMSP-064', category_id: 'OPS-02' },
  { control_id: 'ISMSP-065', category_id: 'LOG-01' },
  { control_id: 'ISMSP-066', category_id: 'LOG-02' },
  { control_id: 'ISMSP-067', category_id: 'LOG-03' },
  { control_id: 'ISMSP-068', category_id: 'NET-02' },
  { control_id: 'ISMSP-069', category_id: 'IAM-05' },
  { control_id: 'ISMSP-070', category_id: 'OPS-05' },
  { control_id: 'ISMSP-071', category_id: 'NET-04' },
  { control_id: 'ISMSP-072', category_id: 'OPS-05' },
  { control_id: 'ISMSP-073', category_id: 'INC-01' },
  { control_id: 'ISMSP-074', category_id: 'LOG-02' },
  { control_id: 'ISMSP-075', category_id: 'INC-04' },
  { control_id: 'ISMSP-076', category_id: 'INC-02' },
  { control_id: 'ISMSP-077', category_id: 'INC-04' },
  { control_id: 'ISMSP-078', category_id: 'BCP-03' },
  { control_id: 'ISMSP-079', category_id: 'BCP-01' },
  { control_id: 'ISMSP-080', category_id: 'BCP-04' },
  { control_id: 'ISMSP-081', category_id: 'DAT-01' },
  { control_id: 'ISMSP-082', category_id: 'DAT-01' },
  { control_id: 'ISMSP-083', category_id: 'DAT-07' },
  { control_id: 'ISMSP-084', category_id: 'DAT-07' },
  { control_id: 'ISMSP-085', category_id: 'DAT-01' },
  { control_id: 'ISMSP-086', category_id: 'DAT-02' },
  { control_id: 'ISMSP-087', category_id: 'DAT-06' },
  { control_id: 'ISMSP-088', category_id: 'DAT-07' },
  { control_id: 'ISMSP-089', category_id: 'DAT-04' },
  { control_id: 'ISMSP-090', category_id: 'DAT-06' },
  { control_id: 'ISMSP-091', category_id: 'DAT-02' },
  { control_id: 'ISMSP-092', category_id: 'DAT-02' },
  { control_id: 'ISMSP-093', category_id: 'DAT-03' },
  { control_id: 'ISMSP-094', category_id: 'DAT-03' },
  { control_id: 'ISMSP-095', category_id: 'DAT-03' },
  { control_id: 'ISMSP-096', category_id: 'DAT-03' },
  { control_id: 'ISMSP-097', category_id: 'DAT-04' },
  { control_id: 'ISMSP-098', category_id: 'DAT-04' },
  { control_id: 'ISMSP-099', category_id: 'DAT-04' },
  { control_id: 'ISMSP-100', category_id: 'DAT-04' },
  { control_id: 'ISMSP-101', category_id: 'DAT-04' },
  { control_id: 'A.5.1', category_id: 'GOV-01' },
  { control_id: 'A.5.2', category_id: 'GOV-02' },
  { control_id: 'A.5.3', category_id: 'HUM-03' },
  { control_id: 'A.5.4', category_id: 'GOV-02' },
  { control_id: 'A.5.5', category_id: 'GOV-04' },
  { control_id: 'A.5.6', category_id: 'GOV-04' },
  { control_id: 'A.5.7', category_id: 'RSK-02' },
  { control_id: 'A.5.8', category_id: 'GOV-04' },
  { control_id: 'A.5.9', category_id: 'AST-01' },
  { control_id: 'A.5.10', category_id: 'AST-03' },
  { control_id: 'A.5.11', category_id: 'AST-03' },
  { control_id: 'A.5.12', category_id: 'AST-04' },
  { control_id: 'A.5.13', category_id: 'AST-04' },
  { control_id: 'A.5.14', category_id: 'AST-04' },
  { control_id: 'A.5.15', category_id: 'IAM-05' },
  { control_id: 'A.5.16', category_id: 'IAM-01' },
  { control_id: 'A.5.17', category_id: 'IAM-02' },
  { control_id: 'A.5.18', category_id: 'IAM-03' },
  { control_id: 'A.5.19', category_id: 'SUP-02' },
  { control_id: 'A.5.20', category_id: 'SUP-01' },
  { control_id: 'A.5.21', category_id: 'SUP-02' },
  { control_id: 'A.5.22', category_id: 'SUP-03' },
  { control_id: 'A.5.23', category_id: 'CLD-01' },
  { control_id: 'A.5.24', category_id: 'INC-01' },
  { control_id: 'A.5.25', category_id: 'INC-02' },
  { control_id: 'A.5.26', category_id: 'INC-03' },
  { control_id: 'A.5.27', category_id: 'INC-04' },
  { control_id: 'A.5.28', category_id: 'INC-03' },
  { control_id: 'A.5.29', category_id: 'BCP-04' },
  { control_id: 'A.5.30', category_id: 'BCP-04' },
  { control_id: 'A.5.31', category_id: 'GOV-04' },
  { control_id: 'A.5.32', category_id: 'GOV-04' },
  { control_id: 'A.5.33', category_id: 'AST-04' },
  { control_id: 'A.5.34', category_id: 'DAT-07' },
  { control_id: 'A.5.35', category_id: 'GOV-03' },
  { control_id: 'A.5.36', category_id: 'GOV-03' },
  { control_id: 'A.5.37', category_id: 'GOV-04' },
  { control_id: 'A.6.1', category_id: 'HUM-01' },
  { control_id: 'A.6.2', category_id: 'HUM-01' },
  { control_id: 'A.6.3', category_id: 'HUM-02' },
  { control_id: 'A.6.4', category_id: 'HUM-04' },
  { control_id: 'A.6.5', category_id: 'HUM-04' },
  { control_id: 'A.6.6', category_id: 'HUM-01' },
  { control_id: 'A.6.7', category_id: 'IAM-06' },
  { control_id: 'A.6.8', category_id: 'INC-02' },
  { control_id: 'A.7.1', category_id: 'PHY-01' },
  { control_id: 'A.7.2', category_id: 'PHY-01' },
  { control_id: 'A.7.3', category_id: 'PHY-02' },
  { control_id: 'A.7.4', category_id: 'PHY-03' },
  { control_id: 'A.7.5', category_id: 'PHY-02' },
  { control_id: 'A.7.6', category_id: 'PHY-01' },
  { control_id: 'A.7.7', category_id: 'PHY-02' },
  { control_id: 'A.7.8', category_id: 'PHY-02' },
  { control_id: 'A.7.9', category_id: 'PHY-04' },
  { control_id: 'A.7.10', category_id: 'AST-03' },
  { control_id: 'A.7.11', category_id: 'PHY-02' },
  { control_id: 'A.7.12', category_id: 'PHY-04' },
  { control_id: 'A.7.13', category_id: 'PHY-04' },
  { control_id: 'A.7.14', category_id: 'AST-03' },
  { control_id: 'A.8.1', category_id: 'OPS-02' },
  { control_id: 'A.8.2', category_id: 'IAM-04' },
  { control_id: 'A.8.3', category_id: 'IAM-05' },
  { control_id: 'A.8.4', category_id: 'IAM-06' },
  { control_id: 'A.8.5', category_id: 'IAM-02' },
  { control_id: 'A.8.6', category_id: 'OPS-03' },
  { control_id: 'A.8.7', category_id: 'OPS-02' },
  { control_id: 'A.8.8', category_id: 'OPS-01' },
  { control_id: 'A.8.9', category_id: 'OPS-01' },
  { control_id: 'A.8.10', category_id: 'DAT-03' },
  { control_id: 'A.8.11', category_id: 'DAT-05' },
  { control_id: 'A.8.12', category_id: 'DAT-06' },
  { control_id: 'A.8.13', category_id: 'BCP-01' },
  { control_id: 'A.8.14', category_id: 'BCP-02' },
  { control_id: 'A.8.15', category_id: 'LOG-01' },
  { control_id: 'A.8.16', category_id: 'LOG-02' },
  { control_id: 'A.8.17', category_id: 'LOG-03' },
  { control_id: 'A.8.18', category_id: 'OPS-04' },
  { control_id: 'A.8.19', category_id: 'OPS-04' },
  { control_id: 'A.8.20', category_id: 'NET-02' },
  { control_id: 'A.8.21', category_id: 'NET-02' },
  { control_id: 'A.8.22', category_id: 'NET-03' },
  { control_id: 'A.8.23', category_id: 'NET-04' },
  { control_id: 'A.8.24', category_id: 'CRY-01' },
  { control_id: 'A.8.25', category_id: 'DEV-01' },
  { control_id: 'A.8.26', category_id: 'DEV-01' },
  { control_id: 'A.8.27', category_id: 'DEV-02' },
  { control_id: 'A.8.28', category_id: 'DEV-03' },
  { control_id: 'A.8.29', category_id: 'DEV-03' },
  { control_id: 'A.8.30', category_id: 'DEV-06' },
  { control_id: 'A.8.31', category_id: 'DEV-04' },
  { control_id: 'A.8.32', category_id: 'DEV-05' },
  { control_id: 'A.8.33', category_id: 'DEV-06' },
  { control_id: 'A.8.34', category_id: 'GOV-03' }
] AS row
MATCH (c:Control {id: row.control_id})
MATCH (cat:Category {id: row.category_id})
MERGE (c)-[:BELONGS_TO]->(cat);


// 07. Secondary Mapping
// 추가 연관 Category를 RELATED_TO로 연결한다.
// 총 58개. 본 매핑은 프로토타입의 수동 의미 판단이며 공식 crosswalk가 아니다.

UNWIND [
  { control_id: 'CASP-007', category_id: 'IAM-03' },
  { control_id: 'CASP-008', category_id: 'IAM-01' },
  { control_id: 'CASP-008', category_id: 'IAM-03' },
  { control_id: 'CASP-009', category_id: 'CLD-01' },
  { control_id: 'CASP-010', category_id: 'AST-01' },
  { control_id: 'CASP-017', category_id: 'IAM-02' },
  { control_id: 'CASP-020', category_id: 'LOG-02' },
  { control_id: 'CASP-027', category_id: 'INC-01' },
  { control_id: 'CASP-028', category_id: 'INC-02' },
  { control_id: 'CASP-029', category_id: 'INC-03' },
  { control_id: 'CASP-030', category_id: 'INC-02' },
  { control_id: 'CASP-031', category_id: 'IAM-03' },
  { control_id: 'CASP-033', category_id: 'IAM-04' },
  { control_id: 'CASP-041', category_id: 'OPS-01' },
  { control_id: 'CASP-042', category_id: 'OPS-01' },
  { control_id: 'CASP-043', category_id: 'OPS-01' },
  { control_id: 'CASP-044', category_id: 'IAM-05' },
  { control_id: 'CASP-044', category_id: 'LOG-01' },
  { control_id: 'CASP-045', category_id: 'NET-03' },
  { control_id: 'CASP-046', category_id: 'CLD-03' },
  { control_id: 'CASP-051', category_id: 'NET-03' },
  { control_id: 'CASP-052', category_id: 'GOV-04' },
  { control_id: 'CASP-053', category_id: 'GOV-04' },
  { control_id: 'CASP-054', category_id: 'CRY-01' },
  { control_id: 'CASP-054', category_id: 'GOV-04' },
  { control_id: 'ISMSP-007', category_id: 'RSK-01' },
  { control_id: 'ISMSP-024', category_id: 'IAM-01' },
  { control_id: 'ISMSP-024', category_id: 'IAM-03' },
  { control_id: 'ISMSP-036', category_id: 'IAM-02' },
  { control_id: 'ISMSP-037', category_id: 'IAM-01' },
  { control_id: 'ISMSP-040', category_id: 'IAM-01' },
  { control_id: 'ISMSP-062', category_id: 'SUP-03' },
  { control_id: 'ISMSP-063', category_id: 'DAT-06' },
  { control_id: 'ISMSP-069', category_id: 'OPS-05' },
  { control_id: 'ISMSP-073', category_id: 'INC-03' },
  { control_id: 'ISMSP-074', category_id: 'INC-02' },
  { control_id: 'ISMSP-086', category_id: 'SUP-02' },
  { control_id: 'ISMSP-087', category_id: 'DAT-07' },
  { control_id: 'ISMSP-088', category_id: 'RSK-01' },
  { control_id: 'ISMSP-090', category_id: 'DAT-02' },
  { control_id: 'ISMSP-092', category_id: 'GOV-04' },
  { control_id: 'ISMSP-093', category_id: 'DAT-02' },
  { control_id: 'A.5.3', category_id: 'IAM-03' },
  { control_id: 'A.5.14', category_id: 'CRY-02' },
  { control_id: 'A.5.23', category_id: 'SUP-03' },
  { control_id: 'A.5.29', category_id: 'INC-01' },
  { control_id: 'A.5.30', category_id: 'BCP-03' },
  { control_id: 'A.6.5', category_id: 'IAM-01' },
  { control_id: 'A.6.5', category_id: 'IAM-03' },
  { control_id: 'A.7.10', category_id: 'DAT-03' },
  { control_id: 'A.7.14', category_id: 'DAT-03' },
  { control_id: 'A.8.10', category_id: 'AST-03' },
  { control_id: 'A.8.12', category_id: 'NET-04' },
  { control_id: 'A.8.18', category_id: 'IAM-04' },
  { control_id: 'A.8.20', category_id: 'NET-01' },
  { control_id: 'A.8.24', category_id: 'CRY-03' },
  { control_id: 'A.8.30', category_id: 'SUP-02' },
  { control_id: 'A.8.34', category_id: 'DEV-03' }
] AS row
MATCH (c:Control {id: row.control_id})
MATCH (cat:Category {id: row.category_id})
MERGE (c)-[:RELATED_TO]->(cat);
