// 07. Secondary Mapping
// 추가 연관 Category를 RELATED_TO로 연결한다.
// 총 58개. 본 매핑은 프로토타입의 수동 의미 판단이며 공식 crosswalk가 아니다.

UNWIND [
  { control_id: 'CASP-007', category_id: 'IAM-03' },
  { control_id: 'CASP-008', category_id: 'IAM-01' },
  { control_id: 'CASP-008', category_id: 'IAM-03' },
  { control_id: 'CASP-009', category_id: 'CLD-01' },
  { control_id: 'CASP-010', category_id: 'AST-01' },
  { control_id: 'CASP-017', category_id: 'IAM-02' },
  { control_id: 'CASP-020', category_id: 'LOG-02' },
  { control_id: 'CASP-027', category_id: 'INC-01' },
  { control_id: 'CASP-028', category_id: 'INC-02' },
  { control_id: 'CASP-029', category_id: 'INC-03' },
  { control_id: 'CASP-030', category_id: 'INC-02' },
  { control_id: 'CASP-031', category_id: 'IAM-03' },
  { control_id: 'CASP-033', category_id: 'IAM-04' },
  { control_id: 'CASP-041', category_id: 'OPS-01' },
  { control_id: 'CASP-042', category_id: 'OPS-01' },
  { control_id: 'CASP-043', category_id: 'OPS-01' },
  { control_id: 'CASP-044', category_id: 'IAM-05' },
  { control_id: 'CASP-044', category_id: 'LOG-01' },
  { control_id: 'CASP-045', category_id: 'NET-03' },
  { control_id: 'CASP-046', category_id: 'CLD-03' },
  { control_id: 'CASP-051', category_id: 'NET-03' },
  { control_id: 'CASP-052', category_id: 'GOV-04' },
  { control_id: 'CASP-053', category_id: 'GOV-04' },
  { control_id: 'CASP-054', category_id: 'CRY-01' },
  { control_id: 'CASP-054', category_id: 'GOV-04' },
  { control_id: 'ISMSP-007', category_id: 'RSK-01' },
  { control_id: 'ISMSP-024', category_id: 'IAM-01' },
  { control_id: 'ISMSP-024', category_id: 'IAM-03' },
  { control_id: 'ISMSP-036', category_id: 'IAM-02' },
  { control_id: 'ISMSP-037', category_id: 'IAM-01' },
  { control_id: 'ISMSP-040', category_id: 'IAM-01' },
  { control_id: 'ISMSP-062', category_id: 'SUP-03' },
  { control_id: 'ISMSP-063', category_id: 'DAT-06' },
  { control_id: 'ISMSP-069', category_id: 'OPS-05' },
  { control_id: 'ISMSP-073', category_id: 'INC-03' },
  { control_id: 'ISMSP-074', category_id: 'INC-02' },
  { control_id: 'ISMSP-086', category_id: 'SUP-02' },
  { control_id: 'ISMSP-087', category_id: 'DAT-07' },
  { control_id: 'ISMSP-088', category_id: 'RSK-01' },
  { control_id: 'ISMSP-090', category_id: 'DAT-02' },
  { control_id: 'ISMSP-092', category_id: 'GOV-04' },
  { control_id: 'ISMSP-093', category_id: 'DAT-02' },
  { control_id: 'A.5.3', category_id: 'IAM-03' },
  { control_id: 'A.5.14', category_id: 'CRY-02' },
  { control_id: 'A.5.23', category_id: 'SUP-03' },
  { control_id: 'A.5.29', category_id: 'INC-01' },
  { control_id: 'A.5.30', category_id: 'BCP-03' },
  { control_id: 'A.6.5', category_id: 'IAM-01' },
  { control_id: 'A.6.5', category_id: 'IAM-03' },
  { control_id: 'A.7.10', category_id: 'DAT-03' },
  { control_id: 'A.7.14', category_id: 'DAT-03' },
  { control_id: 'A.8.10', category_id: 'AST-03' },
  { control_id: 'A.8.12', category_id: 'NET-04' },
  { control_id: 'A.8.18', category_id: 'IAM-04' },
  { control_id: 'A.8.20', category_id: 'NET-01' },
  { control_id: 'A.8.24', category_id: 'CRY-03' },
  { control_id: 'A.8.30', category_id: 'SUP-02' },
  { control_id: 'A.8.34', category_id: 'DEV-03' }
] AS row
MATCH (c:Control {id: row.control_id})
MATCH (cat:Category {id: row.category_id})
MERGE (c)-[:RELATED_TO]->(cat);
